import {scenarioDictionary} from './scenario-english';
import {scenarios,type Scenario} from './scenarios';
import {drills} from './listening-drills';
import {dialogues,type Bilingual} from './dialogues';
const b=(ja:string,en:string):Bilingual=>({ja,en});
export type VoiceProfile={id:string;name:Bilingual;role:Bilingual;age:number;voice:Bilingual;style:Bilingual;pace:number};
export const voiceProfiles:VoiceProfile[]=[
 {id:'elder-haru',name:b('山田 はる','Haru Yamada'),role:b('高齢の女性・利用者','Older female resident'),age:82,voice:b('中低音。やわらかく、温かい響き。自然な息の成分を少し。','Warm, gentle lower-middle female register; slight natural breathiness.'),style:b('穏やかな日常会話。短い句をつなぎ、言い直しは自然に。誇張した震え声や赤ちゃん言葉にしない。','Calm everyday speech, linked short phrases and natural self-corrections. No exaggerated tremor or infantilising delivery.'),pace:.86},
 {id:'elder-masao',name:b('佐藤 正夫','Masao Sato'),role:b('高齢の男性・利用者','Older male resident'),age:79,voice:b('低めで少し乾いた響き。はるさんより張りがあり、落ち着く声。','Lower male register with a slightly dry texture and more vocal firmness than Haru.'),style:b('簡潔で親しみのある話し方。庭や仕事の話では少し生き生きと。語尾を省きすぎない。','Concise, friendly delivery; a little more animated about gardening and work. Keep phrase endings audible.'),pace:.9},
 {id:'elder-fumiko',name:b('田中 文子','Fumiko Tanaka'),role:b('高齢の女性・利用者','Older female resident'),age:86,voice:b('はるさんより少し高い中音域。明るさのある、軽く息を含む声。','A slightly higher middle female register than Haru, bright with light breathiness.'),style:b('思い出を語るときは温かく、訂正はゆっくり明確に。会話全体を弱々しくしない。','Warm when recalling memories; deliberate and clear when correcting. Avoid making every phrase sound frail.'),pace:.84},
 {id:'elder-akira',name:b('鈴木 昭','Akira Suzuki'),role:b('高齢の男性・利用者','Older male resident'),age:84,voice:b('中低音で、子音の輪郭が比較的明瞭。正夫さんとは違う軽いざらつき。','Lower-middle male register with fairly clear consonants and a light rasp distinct from Masao.'),style:b('考えながら話す。いや・じゃなくての前に短い間。語尾は聞こえる音量を保つ。','Thoughtful delivery, with a short pause before iya or ja nakute. Keep the ends of phrases audible.'),pace:.88},
 {id:'care-misaki',name:b('介護士 美咲','Care worker Misaki'),role:b('成人女性・介護士','Adult female care worker'),age:30,voice:b('明瞭な中音域。柔らかいが、はるさんや文子さんより安定した声。','Clear middle female register; gentle and steadier than Haru or Fumiko.'),style:b('丁寧語。成人として尊重し、短く一つずつ確認する。大声・幼児向けの抑揚・機械的な棒読みを避ける。','Respectful polite Japanese. Ask one brief question at a time. No shouting, baby-talk prosody, or robotic delivery.'),pace:.96},
 {id:'care-ken',name:b('介護士 健','Care worker Ken'),role:b('成人男性・介護士','Adult male care worker'),age:35,voice:b('中低音の落ち着いた声。正夫さん・昭さんと区別できる滑らかな響き。','Calm lower-middle male register, smoother and clearly distinct from Masao and Akira.'),style:b('確認の要点をはっきり伝え、返答を待つ。説明は自然な丁寧語。否定や時間の語を落とさない。','Clearly state what is being checked and wait for the reply. Use natural polite Japanese and preserve negation and time words.'),pace:.98},
 {id:'narrator',name:b('学習用ナレーター','Learning narrator'),role:b('成人・解説用','Adult learning narrator'),age:35,voice:b('性別に依存しない明瞭な中音域。登場人物と混同しない別の声。','Clear middle register; a separate neutral voice that cannot be confused with any character.'),style:b('確認後のわかりやすい日本語を自然に読む。役名や制作メモは読まない。','Read the clear Japanese version naturally. Do not read role labels or production notes.'),pace:.94},
];
export type AudioAsset={id:string;storageKey:string;lessonId:string;kind:'short'|'drill'|'turn'|'mix';label:Bilingual;speakerId:string;script:string;direction:Bilingual;filename:string;source:'planned'};
const asset=(id:string,storageKey:string,lessonId:string,kind:AudioAsset['kind'],label:Bilingual,speakerId:string,script:string,direction:Bilingual):AudioAsset=>({id,storageKey,lessonId,kind,label,speakerId,script,direction,filename:id+'.wav',source:'planned'});
export function shortAssets(s:Scenario):AudioAsset[]{const voice=voiceProfiles[s.person%4].id;const output=[asset(`short-${s.id}-original`,s.id,s.id,'short',b('最初の発言','Initial utterance'),voice,s.utterance,b(`場面：${s.setting}。迷いの間を保ち、字幕のことばを足さずに読む。焦点：${s.focus}。`,`Situation: ${scenarioDictionary[s.setting]||s.setting}. Keep the hesitations without adding words. Focus: ${scenarioDictionary[s.focus]||s.focus}.`)),asset(`short-${s.id}-clear`,`short-${s.id}-clear`,s.id,'short',b('確認後の日本語','Clear version after checking'),'narrator',s.plain,b('希望が確認できたあとの、明瞭な日本語。','Clear Japanese after the wish has been checked.'))];
for(const c of s.clarification){const quoted=[...c.text.matchAll(/[『「]([^』」]+)[』」]/g)].map(m=>m[1]).join(' ');if(quoted)output.push(asset(`short-${s.id}-${c.id}-question`,`short-${s.id}-${c.id}-question`,s.id,'short',b('聞き返し・'+c.id,'Clarification · '+c.id),'care-misaki',quoted,b('台詞だけを読む。選択肢の行動説明は読み上げない。質問のあと返答を待つ。','Read the quoted question only, not the description of the action. Leave room for the reply.')));if(c.reply)output.push(asset(`short-${s.id}-${c.id}-reply`,`short-${s.id}-${c.id}-reply`,s.id,'short',b('相手の返答・'+c.id,'Resident reply · '+c.id),voice,c.reply,b(c.correct?'理解された安心感。落ち着いて返答。':'少し戸惑うが、怒鳴らない。別の質問に誘導する返答。',c.correct?'Sound reassured and calm.':'Mildly puzzled, not angry. Indicate that a different question is needed.')));}
for(const c of s.responses){if(s.custom&&c.id==="r-assume")continue;const quoted=[...c.text.matchAll(/[『「]([^』」]+)[』」]/g)].map(m=>m[1]).join(' ');const text=c.id==='r-stop'?quoted:c.text;output.push(asset(`short-${s.id}-${c.id}`,`short-${s.id}-${c.id}`,s.id,'short',b('介護士の返答・'+c.id,'Care worker response · '+c.id),'care-misaki',text,b('正解・不正解のラベルを言わない。誤った返答も普通の声で読む。','Do not speak correctness labels. Read even the unsuitable response in an ordinary voice.')));}
s.variants.forEach((v,i)=>output.push(asset(`short-${s.id}-variant-${i+1}`,`short-${s.id}-variant-${i+1}`,s.id,'short',b('別の言い方 '+(i+1),'Alternative wording '+(i+1)),voice,v,b('同じ話者を維持。元の発言と別の自然な言い方。','Keep the same speaker. Use a natural alternative phrasing.'))));return output;}
export const audioAssets:AudioAsset[]=[...scenarios.flatMap(shortAssets),...drills.map((d,i)=>asset(`drill-${d.id}`,`drill-${d.id}`,d.id,'drill',b('聞き分け '+d.id,'Listening contrast '+d.id),voiceProfiles[Math.floor(i/2)%4].id,d.utterance,b('対になる二つの発言は同じ声・同じ速度。否定・助詞・時間の語を正確に。答えを示す強調は足さない。','Use the same voice and speed for the paired utterances. Preserve negation, particles and time words. Do not add emphasis that gives away the answer.'))),...dialogues.flatMap(d=>[...d.turns.map((t,i)=>asset(`dialogue-${d.id}-t${String(i+1).padStart(2,'0')}`,`dialogue-${d.id}-t${String(i+1).padStart(2,'0')}`,d.id,'turn',b('発話 '+(i+1),'Turn '+(i+1)),t.speaker,t.ja,t.direction)),asset(`dialogue-${d.id}-mix`,`dialogue-${d.id}-mix`,d.id,'mix',b('会話全体・ミックス','Full conversation mix'),'cast',d.turns.map(t=>`[${t.speaker}] ${t.ja}`).join('\n'),b('各発話ファイルを順に結合。役名は読まない。話者の声を固定し、発話間は0.5〜1秒。返答待ちの間は少し長く。','Assemble the ordered turn files. Do not read speaker labels. Keep character voices fixed. Leave 0.5–1 seconds between turns, with a little extra time for replies.'))])];
export const productionRules=b('日本語の台詞を一字一句そのまま読み、英訳・話者名・指示・正誤ラベルは読まない。省略と訂正を勝手に補完しない。声は話者IDに固定し、年齢を理由に極端に不明瞭にしない。明瞭版を先に作り、自然な会話版は同じ台詞で調整する。入れ歯・病気による発音は自動的に再現できると表示しない。BGM・効果音・残響は付けない。省略記号は約0.3〜0.7秒の間。否定・数字・時刻・人名は必ず聞こえるように。マスターは48kHz/モノラルWAV、ウェブ用はMP3も作る。台詞と声の継続性を人が確認してから実装する。','Read the Japanese script verbatim. Do not speak English translations, role names, instructions, or correctness labels. Do not fill in omissions or remove corrections. Fix the voice to the speaker ID; do not make speech extremely unclear merely because a character is older. Produce a clear version first, then a natural conversation version with the same words. Do not claim automatic reproduction of denture- or illness-related speech. No music, effects, or reverb. Treat ellipses as pauses of about 0.3–0.7 seconds. Keep negation, numbers, times, and names audible. Create 48 kHz mono WAV masters and optional MP3 web copies. Human review of the script and voice consistency is required before implementation.');
export function productionPrompt(a:AudioAsset,language:'en'|'ja'='en'):string{const p=voiceProfiles.find(v=>v.id===a.speakerId);return [`Asset ID: ${a.id}`,`Filename: ${a.filename}`,`Storage key: ${a.storageKey}`,`Speaker ID: ${a.speakerId}`,p?`${p.name[language]} · ${p.role[language]} · ${p.age}\nVoice: ${p.voice[language]}\nDelivery: ${p.style[language]}\nRelative pace: ${p.pace}`:'Use the speaker IDs shown in the script and the cast registry; do not read the labels.',`Direction: ${a.direction[language]}`,`Rules: ${productionRules[language]}`,'--- JAPANESE SCRIPT ---',a.script].join('\n\n');}
export function productionBundle(custom:Scenario[]=[]){const assets=[...audioAssets,...custom.flatMap(shortAssets)];return {schemaVersion:1,generatedAudioIncluded:false,voiceProfiles,productionRules,assets,dialogues};}
