"use client";
import {useState} from "react";
import {Headphones,Lightbulb,CheckCircle2,Volume2,RotateCcw} from "lucide-react";
import {Button} from "@/components/ui/button";
import {RadioGroup,RadioGroupItem} from "@/components/ui/radio-group";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {Switch} from "@/components/ui/switch";
import {Textarea} from "@/components/ui/textarea";
import {localize,type Language} from "./localize";
import {drills} from "./listening-drills";
export type DrillRecord={done:number;attempts:number;correct:boolean;subtitle:boolean};
export default function ContrastLab({records,onRecord,onSpeak,onStop,language}:{language:Language;records:Record<string,DrillRecord>;onRecord:(id:string,correct:boolean,subtitle:boolean)=>void;onSpeak:(text:string)=>void;onStop:()=>void}){
 const [group,setGroup]=useState("all");const [onlyMissed,setOnlyMissed]=useState(false);const [index,setIndex]=useState(0);const [selected,setSelected]=useState("");const [checked,setChecked]=useState(false);const [revealed,setRevealed]=useState(false);const [subtitle,setSubtitle]=useState(false);const [note,setNote]=useState("");
 const [reviewIds,setReviewIds]=useState<string[]>([]);
 const groups=[...new Set(drills.map(d=>d.group))];const available=drills.filter(d=>(group==="all"||d.group===group)&&(!onlyMissed||reviewIds.includes(d.id)));const current=available[Math.min(index,available.length-1)];
 const completed=Object.keys(records).filter(id=>drills.some(d=>d.id===id)).length;const correct=Object.values(records).filter(r=>r.correct).length;const missed=drills.filter(d=>records[d.id]?.correct===false).length;
 function reset(){onStop();setSelected("");setChecked(false);setSubtitle(false);setRevealed(false);setNote("");}
 function check(){if(!current||!selected||checked)return;onStop();setChecked(true);onRecord(current.id,Number(selected)===current.answer,subtitle||revealed);}
 return localize(<div className="page-content contrast-page"><div className="page-heading"><div><p className="eyebrow">ONE WORD, DIFFERENT MEANING</p><h1>最後のひとことまで、聞こう。</h1><p className="heading-note">否定・時間・言い直し。似たことばの違いを練習します。</p></div></div>

 <div className="library-toolbar"><Select value={group} onValueChange={v=>{reset();setGroup(v);setIndex(0);}}><SelectTrigger aria-label="聞き分けのテーマ"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">すべてのテーマ</SelectItem>{groups.map(g=><SelectItem key={g} value={g}>{g}</SelectItem>)}</SelectContent></Select><Button variant={onlyMissed?"default":"outline"} onClick={()=>{reset();setReviewIds(drills.filter(d=>records[d.id]?.correct===false).map(d=>d.id));setOnlyMissed(!onlyMissed);setIndex(0);}} aria-pressed={onlyMissed}><RotateCcw size={16}/>間違えた問題だけ</Button><span>{available.length} 問</span></div>
 {current?<div className="contrast-layout"><section className="contrast-desk"><div className="contrast-question-top"><span className="tag">{current.group}</span><span>問題 {Math.min(index,available.length-1)+1} / {available.length}</span></div>{records[current.id]&&<p className="drill-history">前回：{records[current.id].correct?"正解":"要復習"} · {records[current.id].subtitle?"字幕の補助あり":"回答前の字幕なし"} · {records[current.id].attempts} 回回答</p>}<p className="contrast-setting">{current.setting}</p><div className="contrast-listen"><Headphones size={24}/><div><strong>まず、文字を見ずに聞く</strong><p>聞き取れなければ、字幕を使ってかまいません。</p></div><Button onClick={()=>onSpeak(current.utterance)}><Volume2 size={18}/>このことばを聞く</Button></div><div className="subtitle-toggle"><Switch id="contrast-subtitle" checked={subtitle} onCheckedChange={v=>{setSubtitle(v);if(v)setRevealed(true);}}/><label htmlFor="contrast-subtitle">字幕を表示</label></div>{(subtitle||checked)&&<div className="transcript"><span>話したことば</span><p>「{current.utterance}」</p></div>}
 <label className="field-label" htmlFor="contrast-note">聞こえたことば・気になった部分（任意）</label><Textarea id="contrast-note" value={note} onChange={e=>setNote(e.target.value)} maxLength={500} rows={2} placeholder="例：最後が『いらない』に聞こえた"/><h2 className="contrast-prompt">この発言から、わかることは？</h2><RadioGroup value={selected} onValueChange={setSelected} disabled={checked} className="answer-list">{current.options.map((text,i)=><label key={text} className={`answer-option ${selected===String(i)?"selected":""} ${checked&&current.answer===i?"correct":""} ${checked&&selected===String(i)&&current.answer!==i?"incorrect":""}`}><RadioGroupItem value={String(i)} id={`drill-${current.id}-${i}`}/><span><small>{String.fromCharCode(65+i)}</small>{text}</span></label>)}</RadioGroup>
 {!checked?<div className="exercise-actions"><Button disabled={!selected} onClick={check}>意味を確かめる</Button></div>:<><div className={`feedback ${Number(selected)===current.answer?"good":"retry"}`} role="status"><CheckCircle2 size={20}/><div><strong>{Number(selected)===current.answer?"違いを捉えられました":"決め手のことばを、もう一度"}</strong><p><b>手がかり：{current.clue}</b></p><p>{current.explanation}</p><p>聞き返しの例：{current.ask}</p>{note&&<p className="your-note">あなたのメモ：<span data-japanese>{note}</span></p>}</div></div><div className="contrast-compare"><h3>似た発言と、比べて聞く</h3>{drills.filter(d=>d.id.split("-")[0]===current.id.split("-")[0]).map(d=><div key={d.id}><Button variant="ghost" aria-label={`${d.utterance}を聞く`} onClick={()=>onSpeak(d.utterance)}><Volume2 size={17}/></Button><div><strong>「{d.utterance}」</strong><p>{d.options[d.answer]}</p></div></div>)}</div><div className="exercise-actions"><Button onClick={()=>{reset();setIndex(i=>Math.min(i+1,available.length-1));}} disabled={index>=available.length-1}>次の問題</Button><Button variant="outline" onClick={reset}>字幕なしでもう一度</Button></div>{index>=available.length-1&&<p className="small-note">このテーマの最後の問題です。別のテーマか、間違えた問題を選んで続けられます。</p>}</>}
 <div className="question-navigation"><Button variant="ghost" disabled={index===0} onClick={()=>{reset();setIndex(i=>Math.max(0,i-1));}}>前の問題</Button><Button variant="ghost" disabled={index>=available.length-1} onClick={()=>{reset();setIndex(i=>Math.min(i+1,available.length-1));}}>問題をスキップ</Button></div></section><aside className="contrast-aside"><div className="contrast-stats"><div><strong>{completed}<small> / 24</small></strong><span>回答した問題</span></div><div><strong>{correct}</strong><span>直近の回答が正解</span></div><div><strong>{missed}</strong><span>もう一度確かめる</span></div></div><div className="hint-panel"><Lightbulb size={23}/><div><h3>名詞だけで、決めない。</h3><p>何の話かが聞こえても、希望や時間はまだ違うかもしれません。否定と、言い直した後のことばまで聞きます。</p></div></div><div className="contrast-map"><h2>5つの聞きどころ</h2>{groups.map(g=>{const items=drills.filter(d=>d.group===g);const done=items.filter(d=>records[d.id]).length;return <button key={g} onClick={()=>{reset();setGroup(g);setOnlyMissed(false);setIndex(0);}}><span>{g}</span><span>{done} / {items.length}</span></button>;})}</div><p className="small-note">回答時に記録されます。正解数は各問題の直近の初回回答で、字幕の使用も残します。自作の練習例・現場監修待ち。読み上げは高齢者の発音を再現したものではありません。</p></aside></div>:<div className="empty-state"><CheckCircle2 size={32}/><h2>このテーマに、間違えた問題はありません。</h2><Button onClick={()=>{reset();setOnlyMissed(false);setGroup("all");setIndex(0);}}>すべての問題を練習する</Button></div>}
 </div>,language);
}
