import extraDialogues from './content/dialogues-v7.json';
export type Bilingual={ja:string;en:string};
export type Turn={speaker:string;ja:string;en:string;direction:Bilingual};
export type DialogueQuestion={question:Bilingual;options:Bilingual[];answer:number;evidence:number[];why:Bilingual};
export type Dialogue={id:string;title:Bilingual;type:Bilingual;level:number;setting:Bilingual;goal:Bilingual;turns:Turn[];questions:DialogueQuestion[];handover:Bilingual};
const b=(ja:string,en:string):Bilingual=>({ja,en});
const turn=(speaker:string,ja:string,en:string,directionJa="自然な会話。文末まで話し、相手の返答を待つ。",directionEn="Natural conversation. Finish the phrase and leave space for the reply."):Turn=>({speaker,ja,en,direction:b(directionJa,directionEn)});
const q=(ja:string,en:string,options:[string,string][],answer:number,evidence:number[],whyJa:string,whyEn:string):DialogueQuestion=>({question:b(ja,en),options:options.map(([ja,en])=>b(ja,en)),answer,evidence,why:b(whyJa,whyEn)});
const originalDialogues:Dialogue[]=[
 {id:"garden-chat",title:b("庭の花と、昔の仕事","Garden flowers and an old job"),type:b("高齢者同士","Two older residents"),level:1,setting:b("庭が見える居間。はるさんと正夫さんが、鉢植えを見ています。","Haru and Masao are looking at potted flowers from the lounge."),goal:b("話題が花から仕事の思い出へ変わるところを追う。","Follow a change of topic from flowers to memories of work."),turns:[
 turn('elder-haru','あの花、今年もよく咲いたねえ。','Those flowers have bloomed well again this year.'),
 turn('elder-masao','うん。でも、あっちの白いのは、まだだね。','Yes. But the white ones over there have not bloomed yet.'),
 turn('elder-haru','白いの？ ああ、窓の近くの、あれね。','The white ones? Oh, the ones near the window.'),
 turn('elder-masao','そうそう。去年は、もう咲いてたと思うんだけど。','Yes. I think they had already bloomed by this time last year.'),
 turn('elder-haru','今年は寒かったからね。もう少し、待とうか。','It was cold this year. Let’s wait a little longer.'),
 turn('elder-masao','うちにも、昔、こんな鉢があってね。','We used to have pots like these at home.'),
 turn('elder-haru','お庭で育ててたの？','Did you grow them in the garden?'),
 turn('elder-masao','いや、庭じゃなくて、店の前。小さな店だったんだ。','No, not in the garden. In front of our small shop.','「庭じゃなくて」で穏やかに訂正。店の前を明瞭に。','Gently correct garden; articulate in front of the shop clearly.'),
 turn('elder-haru','お店？ 何のお店だったの。','A shop? What kind of shop?'),
 turn('elder-masao','花…じゃないよ。靴を直す店。父と二人でね。','Not a flower shop. A shoe-repair shop. My father and I ran it.','花のあと少し間を置き、靴を直す店をはっきり言う。','Pause briefly after flowers, then clearly say shoe-repair shop.'),
 turn('elder-haru','ああ、靴屋さん。長いこと、やってたのね。','Oh, a shoe shop. You did that for a long time.'),
 turn('elder-masao','売るほうじゃなくて、修理だよ。三十年くらいかな。','We repaired shoes rather than selling them. About thirty years.'),
 turn('elder-haru','ごめんね、修理のお店ね。手が器用だったんだね。','Sorry, a repair shop. You must have been good with your hands.'),
 turn('elder-masao','今も、何か直せそうな気がするよ。','I still feel as if I could repair something.'),
 turn('elder-haru','私は、縫うのが好きだった。服のほつれをね。','I liked sewing, especially repairing loose seams.'),
 turn('elder-masao','じゃあ、二人で修理屋だ。靴と服と。','Then we’d make a repair team: shoes and clothes.'),
 turn('elder-haru','いいねえ。でも今日は、お花を見て休もう。','That sounds nice. But today let’s rest and enjoy the flowers.'),
 turn('elder-masao','そうだね。白い花が咲いたら、また一緒に見よう。','Yes. Let’s look at the white flowers together when they bloom.')],questions:[
 q('鉢植えがあったのは、どこ？','Where were Masao’s old flower pots?', [['庭','In the garden'],['店の前','In front of the shop'],['居間の窓際','By the lounge window']],1,[6,7],'庭という推測は、正夫さんが訂正しています。','Masao corrects the suggestion that the pots were in a garden.'),
 q('正夫さんの仕事は？','What work did Masao do?', [['花を売る','Selling flowers'],['靴を売る','Selling shoes'],['靴を修理する','Repairing shoes']],2,[9,11],'花屋でも販売の靴屋でもなく、修理のお店です。','He rules out both a flower shop and selling shoes; he repaired shoes.'),
 q('白い花は、今どうなっている？','What is true of the white flowers now?', [['まだ咲いていない','They have not bloomed yet'],['もう枯れた','They have already withered'],['去年は咲かなかった','They did not bloom last year']],0,[1,3,17],'去年の話と、今年まだ咲いていない話を分けます。','Separate the memory of last year from the current flowers.')],handover:b("正夫さんは、以前父親と靴の修理店を営んでいたと話された。はるさんと庭の花を眺め、白い花が咲いたらまた一緒に見たいと会話された。","Masao said he used to run a shoe-repair shop with his father. He and Haru enjoyed looking at flowers and talked about seeing the white flowers together after they bloom.")},
 {id:"photo-chat",title:b("写真の人と、訪問の予定","A family photo and a visit"),type:b("高齢者同士","Two older residents"),level:2,setting:b("文子さんと昭さんが、文子さんのアルバムを見ています。","Fumiko and Akira are looking through Fumiko’s photo album."),goal:b("誰の家族か、言い直しと伝聞を区別する。","Track whose family is being discussed, corrections, and reported plans."),turns:[
 turn('elder-fumiko','この子、ずいぶん大きくなったでしょう。','This child has grown a lot, hasn’t he?'),
 turn('elder-akira','娘さん？ 前にも、写真を見せてくれたよね。','Your daughter? You showed me a photo before.'),
 turn('elder-fumiko','娘…じゃなくて、孫。この青い服の子。','Not my daughter, my grandson. The one in blue.'),
 turn('elder-akira','ああ、お孫さん。今は、中学生かな。','Oh, your grandson. Is he in junior high now?'),
 turn('elder-fumiko','去年まではね。今は高校一年生よ。','He was last year. Now he is in his first year of high school.'),
 turn('elder-akira','そうか。うちの孫も高校生なんだ。','I see. My grandchild is in high school too.'),
 turn('elder-fumiko','お宅のお孫さん、女の子だったね。','Your grandchild is a girl, right?'),
 turn('elder-akira','そう。遠くに住んでるから、なかなか会えなくて。','Yes. She lives far away, so I don’t see her very often.'),
 turn('elder-fumiko','私は、この子が日曜に来るんだって。娘から聞いたの。','I heard this boy is coming on Sunday. My daughter told me.'),
 turn('elder-akira','日曜か。明日じゃないの？','Sunday? Not tomorrow?'),
 turn('elder-fumiko','明日は土曜でしょう。来るのは、その次の日。','Tomorrow is Saturday, isn’t it? He’s coming the following day.'),
 turn('elder-akira','あ、そうだ。日曜日ね。何時ごろ？','Oh, yes. Sunday. Around what time?'),
 turn('elder-fumiko','そこは、まだ聞いてない。お昼のあとだと、いいけど。','I haven’t heard that yet. After lunch would be nice, though.'),
 turn('elder-akira','じゃあ、お昼のあとに来る予定？','Then is he scheduled to come after lunch?'),
 turn('elder-fumiko','予定じゃなくて、私がそう思ってるだけ。時間は、まだ。','No, that’s only what I’d prefer. The time is still unknown.','希望と確定した予定を区別。時間はまだを明瞭に。','Clearly distinguish a preference from a confirmed plan; time is still unknown.'),
 turn('elder-akira','そうだったね。勝手に決めちゃいけないね。','Right. I shouldn’t assume the time.'),
 turn('elder-fumiko','写真を見せながら、学校の話を聞きたいの。','I want to show him these photos and hear about school.'),
 turn('elder-akira','楽しみだね。職員さんにも、日曜のことは伝えた？','That sounds nice. Have you told staff about Sunday?'),
 turn('elder-fumiko','まだなの。あとで娘に時間を聞いて、それから。','Not yet. I’ll ask my daughter the time, then tell staff.'),
 turn('elder-akira','うん。それなら、時間も一緒に伝えられるね。','Then you can tell them the time as well.')],questions:[
 q('アルバムの青い服の人は？','Who is the person in blue in Fumiko’s album?', [['昭さんの孫娘','Akira’s granddaughter'],['文子さんの娘','Fumiko’s daughter'],['文子さんの孫','Fumiko’s grandson']],2,[0,2,6],'二人の家族の話が混ざります。青い服の人は文子さんの孫です。','Both families are discussed. The person in blue is Fumiko’s grandson.'),
 q('訪問時間について確定していることは？','What is confirmed about the visit time?', [['昼食後に確定','Definitely after lunch'],['時間はまだ不明','The time is still unknown'],['明日の朝に確定','Definitely tomorrow morning']],1,[12,14,18],'昼食後は希望です。時間を聞いたわけではありません。','After lunch is a preference, not an established time.'),
 q('職員にも確認済みの予定と言える？','Can we say the visit has been confirmed with staff?', [['確認済みと言える','Yes, it is confirmed'],['娘から聞いたので職員確認も不要','Staff confirmation is unnecessary'],['まだ職員に伝えていない','She has not told staff yet']],2,[8,17,18],'本人が娘から聞いた情報と、職員側の確認を分けます。','Distinguish what her daughter said from confirmation with staff.')],handover:b("文子さんは娘から、孫が日曜に来ると聞いたと話された。昼食後を希望しているが訪問時刻は未確認。まだ職員には伝えておらず、娘に時刻を尋ねてから伝える意向。","Fumiko said her daughter told her the grandson would visit on Sunday. She prefers after lunch, but the time is unconfirmed. She plans to ask her daughter and then inform staff.")},
 {id:"tea-jacket",title:b("お茶の希望から、午後のお願いへ","From tea to an afternoon request"),type:b("高齢者と介護士","An older resident and a care worker"),level:1,setting:b("午前のおやつ。はるさんと介護士の美咲さんが話しています。","During the morning snack, Haru speaks with care worker Misaki."),goal:b("途中で変わる希望と、今すること・後ですることを追う。","Follow changing requests and distinguish now from later."),turns:[
 turn('care-misaki','はるさん、飲み物はいかがですか。','Haru, would you like something to drink?'),
 turn('elder-haru','水…いや、お茶がいいね。あったかいの。','Water… no, tea would be nice. Warm tea.'),
 turn('care-misaki','温かいお茶ですね。量はどのくらいにしましょうか。','Warm tea. How much would you like?'),
 turn('elder-haru','ちょっとだけ。いっぱいは、いらないよ。','Just a little. I don’t need a full cup.'),
 turn('care-misaki','このくらいで、よいですか。','Is about this much enough?'),
 turn('elder-haru','うん、ちょうどいい。いつも、悪いねえ。','Yes, just right. Sorry to trouble you as always.'),
 turn('care-misaki','どういたしまして。ほかに何かありますか。','You’re welcome. Is there anything else?'),
 turn('elder-haru','そこの…黄色いの。今、ひざに。','The yellow one over there. On my lap now.'),
 turn('care-misaki','この黄色いひざ掛けですか。','This yellow lap blanket?'),
 turn('elder-haru','そう。少し、冷えるから。','Yes. It feels a little chilly.'),
 turn('care-misaki','ひざに掛けますね。このくらいで、どうですか。','I’ll put it on your lap. How does that feel?'),
 turn('elder-haru','いいよ。あと、上着も…でも、今じゃない。','Good. And my jacket too… but not now.'),
 turn('care-misaki','上着は、あとにしますか。','The jacket later, then?'),
 turn('elder-haru','ごはんのあと。庭に出るなら、着たいの。','After the meal. I’d like it if I go into the garden.'),
 turn('care-misaki','昼食のあと、庭に出るときに上着を着たいのですね。','You’d like the jacket after lunch, when going into the garden?'),
 turn('elder-haru','うん。でも、雨なら、ここでいいよ。','Yes. But if it rains, I’ll stay here.'),
 turn('care-misaki','天気を確認して、昼食のあとにまたお声をかけますね。','I’ll check the weather and ask you again after lunch.'),
 turn('elder-haru','お願い。今は、このお茶を飲んで、少し休むね。','Please do. For now I’ll have this tea and rest a little.')],questions:[
 q('今希望している飲み物は？','Which drink does Haru want now?', [['冷たい水をたくさん','A lot of cold water'],['温かいお茶を少し','A little warm tea'],['飲み物はいらない','No drink']],1,[1,3,5],'最初の水ではなく、訂正後のお茶。量は少しです。','Use the correction to tea, and the request for a small amount.'),
 q('今することと、後ですることは？','Which action is for now, and which is for later?', [['今はひざ掛け、上着は昼食後に再確認','Blanket now; jacket checked again after lunch'],['今すぐ上着、ひざ掛けは明日','Jacket now; blanket tomorrow'],['両方今すぐ','Both immediately']],0,[7,11,13,16],'上着は今じゃないという訂正を残します。','Keep the correction that the jacket is not for now.'),
 q('庭に出ることは、確定している？','Is going into the garden definite?', [['天気に関係なく確定','Yes, whatever the weather'],['雨の日だけ行く','Only if it rains'],['雨なら居間にいる希望','She prefers staying inside if it rains']],2,[13,15,16],'外出には条件があり、天気はこれから確認します。','The outing is conditional; the weather still needs checking.')],handover:b("はるさんは温かいお茶を少量希望。黄色いひざ掛けを今ひざに掛けたいと確認。上着は昼食後、庭に出る場合に希望し、雨なら居間でよいとのこと。天気確認後に再度声をかける予定。","Haru wanted a little warm tea and the yellow blanket on her lap now. She wants the jacket after lunch if going into the garden, and prefers staying in the lounge if it rains. A follow-up after checking the weather is planned.")},
 {id:"outing-plan",title:b("散歩の時間と、天気の条件","A walk, its timing, and the weather"),type:b("高齢者と介護士","An older resident and a care worker"),level:2,setting:b("正夫さんが、翌日の散歩について介護士の健さんに尋ねます。","Masao asks care worker Ken about a walk the following day."),goal:b("最初の提案から訂正された時間と、条件付きの希望を区別する。","Track a corrected time and a conditional preference."),turns:[
 turn('elder-masao','明日、外へ行けるかな。花を、近くで見たいんだ。','Could I go outside tomorrow? I’d like to see the flowers up close.'),
 turn('care-ken','明日の天気と予定を確認しますね。午前がよいですか。','I’ll check tomorrow’s weather and schedule. Would morning suit you?'),
 turn('elder-masao','午前…いや、ごはんのあとがいい。','Morning… no, after the meal would be better.'),
 turn('care-ken','昼食のあと、ということですね。','After lunch, then?'),
 turn('elder-masao','そう。朝は、のんびり新聞を読みたいから。','Yes. In the morning I want to take my time reading the newspaper.'),
 turn('care-ken','わかりました。どのあたりを見たいですか。','Of course. Which part would you like to see?'),
 turn('elder-masao','あの…奥の、白い花。まだ咲いてないのも、あるよね。','The white flowers at the back. Some haven’t bloomed yet.'),
 turn('care-ken','庭の奥にある白い花のところですね。','The white flowers at the back of the garden?'),
 turn('elder-masao','うん。長く歩きたいわけじゃないよ。そこまででいい。','Yes. I don’t want a long walk. Just as far as those flowers.'),
 turn('care-ken','短い時間、花のところまで行きたいのですね。','You want a short outing as far as the flowers?'),
 turn('elder-masao','でも、雨なら、やめよう。晴れたら、お願い。','But let’s not go if it rains. Only if it’s sunny.'),
 turn('care-ken','晴れた場合に、昼食後の短い散歩をご希望ですね。','A short walk after lunch if it’s sunny, then.'),
 turn('elder-masao','そう。今日じゃなくて、明日ね。','Yes. Tomorrow, not today.'),
 turn('care-ken','明日ですね。まだ予定は確定していないので、担当の職員と確認します。','Tomorrow. The plan is not confirmed yet, so I’ll check with the responsible staff member.'),
 turn('elder-masao','うん、決まったら、教えて。','All right. Let me know when it’s decided.'),
 turn('care-ken','確認してから、お伝えします。雨なら、居間から花を見ましょうか。','I’ll tell you after checking. If it rains, would you like to view the flowers from the lounge?'),
 turn('elder-masao','それもいいね。窓の近くの席なら、見えるから。','That would be nice too. They’re visible from a seat near the window.'),
 turn('care-ken','そのご希望も、担当の職員に伝えますね。','I’ll pass that preference to the responsible staff member too.')],questions:[
 q('訂正された希望の時間は？','What is the corrected preferred time?', [['今日の午前','This morning'],['明日の昼食後','After lunch tomorrow'],['明日の朝食前','Before breakfast tomorrow']],1,[2,3,12],'午前という最初の提案と、昼食後という訂正を分けます。','Distinguish the morning suggestion from the corrected preference for after lunch.'),
 q('希望する散歩の長さは？','What kind of walk does Masao want?', [['庭の奥の花まで、短い散歩','A short walk as far as the flowers at the back'],['施設の外を長く歩く','A long walk outside the facility'],['花には近づかない','A walk avoiding the flowers']],0,[6,8,9],'行き先と長さを、本人が具体的に説明しています。','He states both the destination and that he does not want a long walk.'),
 q('今の予定の状態は？','What is the current status of the plan?', [['必ず実施すると職員が約束した','Staff have promised it will definitely happen'],['本人は雨なら外へ行きたい','He wants to go out if it rains'],['希望は確認したが、職員側の調整はこれから','Preferences are checked; staff arrangements are still pending']],2,[10,13,15],'希望の確認と、実施の確定は別です。','Checking a wish is not the same as confirming the arrangements.')],handover:b("正夫さんは明日の昼食後、晴れたら庭の奥の白い花まで短い散歩を希望。雨なら外出せず、窓際から花を見たいとのこと。実施予定は未確定で、担当職員と確認してから本人へ伝える。","Masao wants a short walk to the white flowers after lunch tomorrow if sunny. If it rains, he prefers viewing the flowers from the window. Arrangements are not confirmed; staff will check and report back.")},
 {id:"phone-message",title:b("電話の伝言を、最後まで確かめる","Checking a telephone message from start to finish"),type:b("高齢者と介護士","An older resident and a care worker"),level:3,setting:b("はるさんが、娘への電話について美咲さんに相談します。","Haru asks Misaki about a telephone call to her daughter."),goal:b("電話の向き・相手・時間を、途中の訂正も含めて追う。","Track who is calling whom, when, and how the request changes."),turns:[
 turn('elder-haru','さっきの人に…娘、電話ね。お願い。','That person from earlier… my daughter, the phone. Please.'),
 turn('care-misaki','娘さんから電話があった、ということですか。','Do you mean your daughter called?'),
 turn('elder-haru','違うの。私から、娘へ。話したいのよ。','No. From me to my daughter. I want to talk to her.'),
 turn('care-misaki','娘さんに電話をしたいのですね。','You would like to call your daughter.'),
 turn('elder-haru','そう。それを、さっきの職員さんに伝えて。','Yes. Please tell the staff member I spoke to earlier.'),
 turn('care-misaki','先ほど、お部屋でお話しした職員ですか。','The staff member who spoke with you in your room?'),
 turn('elder-haru','部屋…じゃなくて、ここ。居間でね。','Not in my room, here in the lounge.'),
 turn('care-misaki','居間で話した職員ですね。お名前はわかりますか。','The one you spoke to in the lounge. Do you know the name?'),
 turn('elder-haru','名前は、ちょっと…。青い名札の人。','I can’t quite remember the name. The one with a blue name badge.'),
 turn('care-misaki','青い名札ですね。誰かを確認してから、お伝えします。','A blue name badge. I’ll check which staff member it was before passing the message on.'),
 turn('elder-haru','今すぐ…いや、娘は仕事だね。夕方がいいかな。','Right now… no, my daughter is at work. Maybe evening would be better.'),
 turn('care-misaki','今ではなく、夕方に電話したいのですね。','You’d like to call in the evening, not now.'),
 turn('elder-haru','うん。でも、何時に帰るかは、知らないの。','Yes. But I don’t know what time she gets home.'),
 turn('care-misaki','娘さんの都合のよい時刻は、まだわからないのですね。','We don’t know what time would suit your daughter yet.'),
 turn('elder-haru','そう。もし忙しかったら、また別の日でもいいよ。','Right. If she’s busy, another day would be fine.'),
 turn('care-misaki','夕方を希望していて、娘さんが忙しければ別の日でもよい、ということですね。','You prefer evening, but another day is fine if your daughter is busy.'),
 turn('elder-haru','そうそう。写真のこと、聞きたいだけだから。','Exactly. I only want to ask about the photographs.'),
 turn('care-misaki','どの写真のお話ですか。','Which photographs do you mean?'),
 turn('elder-haru','この前、孫が送ってくれた写真。娘じゃなくて、孫から。','The photos my grandchild sent recently. From my grandchild, not my daughter.'),
 turn('care-misaki','お孫さんから届いた写真について、娘さんに聞きたいのですね。','You want to ask your daughter about photographs sent by your grandchild.'),
 turn('elder-haru','うん。まずは、職員さんに電話したいって伝えてね。','Yes. First, please tell that staff member I want to make a call.'),
 turn('care-misaki','わかりました。相手の職員と、電話の時間を確認してから、またお声をかけます。','Of course. I’ll check the staff member and the call time, then speak to you again.')],questions:[
 q('誰が誰へ電話したい？','Who wants to call whom?', [['娘がはるさんへ','Her daughter wants to call Haru'],['はるさんが娘へ','Haru wants to call her daughter'],['孫が職員へ','Her grandchild wants to call staff']],1,[0,2,3],'最初の職員の推測は、はるさんが訂正しています。','Haru corrects the care worker’s initial interpretation of the direction.'),
 q('電話の時刻について、どこまでわかる？','What do we know about the call time?', [['今すぐに確定','It is definitely now'],['夕方の希望だが具体的時刻は未確認','Evening is preferred; the exact time is unconfirmed'],['明日の午前に確定','It is definitely tomorrow morning']],1,[10,12,14,15],'夕方は希望です。娘の都合がよい時刻はまだ不明です。','Evening is a preference. The daughter’s availability is still unknown.'),
 q('写真を送った人と、伝言先の職員は？','Who sent the photos, and is the staff recipient identified?', [['娘が送り、職員の名前も確定','The daughter sent them; staff name is confirmed'],['孫が送り、職員の名前はまだ不明','The grandchild sent them; staff name is unknown'],['職員が送り、娘の名前が不明','Staff sent them; the daughter’s name is unknown']],1,[8,9,18,19],'写真の送り手と、電話相手と、伝言先を混同しません。','Keep the photo sender, call recipient, and staff recipient separate.')],handover:b("はるさんは娘へ電話したいと希望。今ではなく夕方を希望するが、娘の都合のよい時刻は未確認。忙しければ別の日でもよいとのこと。孫から届いた写真について娘に尋ねたい。居間で先ほど話した青い名札の職員へ伝言を希望するが、職員名は未確認。","Haru wants to call her daughter in the evening, rather than now. The daughter’s availability is unconfirmed; another day is acceptable if she is busy. Haru wants to ask about photos sent by her grandchild. The intended staff recipient has a blue name badge and spoke with her in the lounge, but their name is not yet identified.")},
 {id:"three-people",title:b("三人の会話で、希望を取り違えない","Three people, three different requests"),type:b("高齢者二人と介護士","Two older residents and a care worker"),level:3,setting:b("午後の居間。はるさん、正夫さん、健さんが話しています。","Haru, Masao, and Ken are talking in the lounge in the afternoon."),goal:b("誰が何を希望したか、他の人の希望と分けて記録する。","Keep each person’s request separate as the conversation shifts."),turns:[
 turn('care-ken','お二人とも、飲み物はいかがですか。','Would either of you like a drink?'),
 turn('elder-haru','私は、温かいお茶。少しだけね。','I’d like warm tea. Just a little.'),
 turn('elder-masao','僕は水…いや、やっぱりお茶。冷たいほう。','Water for me… no, tea after all. Cold tea.'),
 turn('care-ken','はるさんは温かいお茶を少し。正夫さんは冷たいお茶ですね。','A little warm tea for Haru, and cold tea for Masao.'),
 turn('elder-masao','うん。僕のは、半分くらいでいい。','Yes. About half a cup for mine.'),
 turn('elder-haru','あら、冷たいの、平気なの？','Oh, are you happy with a cold drink?'),
 turn('elder-masao','今日はね。温かいのは、あとでいいかな。','Today, yes. Maybe I’ll have a warm drink later.'),
 turn('care-ken','今は冷たいお茶ですね。あとで変えたくなったら、教えてください。','Cold tea for now. Let me know if you want something different later.'),
 turn('elder-haru','あと、そこの黄色いの。ひざに掛けてほしい。','Also, the yellow thing there. I’d like it on my lap.'),
 turn('care-ken','この黄色いひざ掛けですね。はるさんのひざに掛けます。','This yellow lap blanket. I’ll put it on Haru’s lap.'),
 turn('elder-masao','僕は、それはいらないよ。窓だけ、少し閉めたい。','I don’t need that. I’d just like the window closed a little.'),
 turn('care-ken','正夫さんはひざ掛けは不要で、窓を少し閉めたいのですね。','Masao does not want a blanket, but wants the window closed a little.'),
 turn('elder-haru','全部は閉めないでね。お花が見たいから。','Please don’t close it completely. I want to see the flowers.'),
 turn('elder-masao','窓を閉めても、ガラス越しに見えるよ。カーテンじゃないんだ。','You can see them through the glass. I mean the window, not the curtain.'),
 turn('care-ken','閉めるのは窓ですね。カーテンは開けたままでよいですか。','The window, then. Shall I keep the curtain open?'),
 turn('elder-haru','あ、そうだった。カーテンは、そのままでお願い。','Oh, of course. Please leave the curtain as it is.'),
 turn('elder-masao','うん。窓は、少しだけ。風が強いから。','Yes. Close the window just a little because of the strong draft.'),
 turn('care-ken','窓を少し閉めます。このくらいで、どうですか。','I’ll close it a little. How about this?'),
 turn('elder-masao','それでいい。ありがとう。','That’s fine. Thank you.'),
 turn('elder-haru','私も、ちょうどいいよ。あったかくなったね。','That suits me too. It feels warmer now.'),
 turn('care-ken','お茶もお持ちしました。温かいほうが、はるさんです。','Here is the tea. The warm one is for Haru.'),
 turn('elder-masao','僕は冷たいほうね。半分くらい。','And the cold one is mine, about half a cup.'),
 turn('care-ken','はい。ひざ掛けと窓も、ご希望の状態になっていますか。','Yes. Are the blanket and window as you wanted?'),
 turn('elder-haru','うん、ありがとう。しばらく、ここで花を見てるね。','Yes, thank you. I’ll stay here and look at the flowers for a while.')],questions:[
 q('二人の飲み物の希望は？','Which drink does each person want?', [['はるさんは温かいお茶を少し、正夫さんは冷たいお茶を半分ほど','Haru: a little warm tea; Masao: about half a cup of cold tea'],['二人とも温かい水をいっぱい','Both: a full cup of warm water'],['はるさんは冷たいお茶、正夫さんは温かいお茶','Haru: cold tea; Masao: warm tea']],0,[1,2,4,7],'正夫さんの最初の水と、あとでの温かい飲み物を現在の希望と混ぜません。','Do not mix Masao’s first suggestion of water or a possible later warm drink with his current request.'),
 q('ひざ掛けを希望したのは誰？','Who wanted the lap blanket?', [['二人とも','Both residents'],['正夫さんだけ','Masao only'],['はるさんだけ','Haru only']],2,[8,9,10],'同じ居間でも、希望は人ごとに違います。','People in the same room can have different wishes.'),
 q('窓とカーテンはどうする？','What should happen to the window and curtain?', [['両方全部閉める','Close both completely'],['窓を少し閉め、カーテンはそのまま','Close the window a little; leave the curtain as it is'],['窓を開け、カーテンだけ閉める','Open the window; close only the curtain']],1,[12,13,14,15,16],'はるさんの花を見たい希望は、カーテンと窓の区別で整理されます。','Distinguishing the window from the curtain resolves the concern about seeing the flowers.')],handover:b("はるさんは温かいお茶を少量、黄色いひざ掛けを希望。正夫さんは冷たいお茶を半分ほど希望し、ひざ掛けは不要。窓は少し閉め、カーテンは開けたままと確認。各本人から希望の状態であることを確認した。","Haru wanted a little warm tea and the yellow lap blanket. Masao wanted about half a cup of cold tea and no blanket. They agreed to close the window a little and leave the curtain open. Each person’s preference was checked separately.")},
];

export const dialogues:Dialogue[]=[...originalDialogues,...extraDialogues];
