import extraDrills from './content/drills-v7.json';
import {drills} from './listening-drills';
const rows:Record<string,string[]>={
need:["You asked whether to bring tea.","They want tea.","They do not want tea.","They are specifying the temperature of the tea.","Do not decide from the noun alone. Listen to the final words that tell you whether the item is wanted.","Shall I bring tea?","You don't want tea right now, is that right?"],
yet:["During a meal, you asked whether to clear the dishes.","They intend to continue eating.","They do not intend to eat any more.","We know why they are finishing their meal.","Listen to mada (still), mou (already / any more), and whether the verb is negative. These words do not establish the reason for stopping.","Shall I leave the dishes here for now?","May I clear the dishes?"],
before:["You are discussing when to put on a jacket.","They want to put on the jacket before the meal.","They want to put on the jacket after the meal.","They do not want to wear a jacket.","The jacket is the same, but the time word changes the order of the actions.","Before the meal?","After the meal?"],
past:["You are talking about a family visit.","They say their daughter visited yesterday.","They say their daughter will visit tomorrow.","They are not saying when their daughter will visit.","Listen to the time word and verb form together. A person's statement alone does not confirm a future visit with the facility.","Your daughter visited yesterday, then?","Your daughter is planning to visit tomorrow, then?"],
rain:["You are discussing plans to go outside.","They want to cancel the outing if it rains.","They want to go out even if it rains.","They are refusing the outing regardless of the weather.","Nara introduces a condition. Demo here means even if that condition applies.","If it rains, would you rather stay inside?","You want to go outside even if it rains, is that right?"],
side:["There is one red book on each side of the shelf.","They want the red book on the right.","They want the red book on the left.","They do not want a red book.","Colour alone does not identify the book. Show the actual object and check whose viewpoint determines right and left.","Is this red book the right one?","Is this red book the right one?"],
amount:["You are discussing how much tea to put in the cup.","They want a small amount.","They want a little more than the current amount.","They want all the tea cleared away.","Dake limits the amount. Mou requests an additional amount. The similar phrases mean different things.","Is this small amount enough?","Would you like a little more?"],
curtain:["They have made a request about the curtain.","They want the curtain opened a little.","They want the curtain closed a little.","They want the curtain completely removed.","The object and amount are the same, but the actions are opposites. Do not act based only on the noun.","Shall I open it a little?","Shall I close it a little?"],
call:["They are trying to tell a staff member about a telephone call.","They are reporting a call from their daughter.","They are asking for a call to their daughter.","It is certain that the other person on the call is a staff member.","Kara marks the source; e marks the destination. The final words also distinguish a report from a request.","Your daughter called, is that right?","You would like to call your daughter, is that right?"],
repair:["You are asking which drink they want.","After correcting themselves, they want tea.","After correcting themselves, they want water.","They want both drinks.","Do not keep the first noun after a correction. Listen to what follows ja nakute (not that, but…).","Tea, then?","Water, then?"],
family:["You are looking at a family photograph.","After correcting themselves, they say it is their grandchild.","After correcting themselves, they say it is their daughter.","We know that both their daughter and grandchild are in the photograph.","Iya marks a correction here. Do not mix the first claim with the corrected information.","This is your grandchild, then?","This is your daughter, then?"],
which:["A lap blanket and a jacket are next to the chair.","They feel cold, but the wanted item is not yet identified.","They are asking for the lap blanket.","It is certain that they want the jacket.","Sore (that) does not identify the object by itself. Even with a clear noun, check any remaining details such as how they want to use it.","Show the lap blanket and ask, 'Is this it?'","Shall I put it on your lap?"],
};
Object.assign(rows,Object.fromEntries(extraDrills.map(x=>[x.pair.id,x.englishRows])));
export const drillDictionary:Record<string,string>={};
for(const d of drills){const e=rows[d.id.split('-')[0]];const pair=drills.filter(n=>n.id.split('-')[0]===d.id.split('-')[0]);if(!e)continue;drillDictionary[d.setting]=e[0];drillDictionary[pair[0].options[pair[0].answer]]=e[1];drillDictionary[pair[1].options[pair[1].answer]]=e[2];const trap=d.options.find(o=>!pair.some(n=>n.options[n.answer]===o));if(trap)drillDictionary[trap]=e[3];drillDictionary[d.explanation]=e[4];drillDictionary[d.ask]=d.ask+'\n'+e[Number(d.id.split('-')[1])+5];}
