import extraDrills from './content/drills-v7.json';
export type Drill={id:string;group:string;setting:string;utterance:string;options:string[];answer:number;clue:string;explanation:string;ask:string};
type Pair={id:string;group:string;setting:string;lines:[string,string];meanings:[string,string];clues:[string,string];explanation:string;asks:[string,string];trap:string};
const pairs:Pair[]=[
 {id:"need",group:"否定",setting:"お茶をお持ちするか、たずねました。",lines:["お茶…いるよ。","お茶…いらないよ。"],meanings:["お茶を希望している。","お茶を希望していない。"],clues:["いる","いらない"],explanation:"物の名前だけで判断せず、必要かどうかを表す最後のことばまで聞きます。",asks:["お茶をお持ちしますか？","今はお茶はいらない、ということですね？"],trap:"お茶の温度を指定している。"},
 {id:"yet",group:"否定",setting:"食事中、食器を下げてよいか、たずねました。",lines:["まだ…食べるよ。","もう…食べないよ。"],meanings:["食事を続けるつもり。","これ以上は食べないつもり。"],clues:["まだ・食べる","もう・食べない"],explanation:"『まだ』と『もう』に加え、動詞の否定も聞きます。食事を終えた理由までは断定できません。",asks:["食器はまだ下げずに置いておきますか？","食器を下げてもよいですか？"],trap:"食事を終える理由がわかった。"},
 {id:"before",group:"時間・条件",setting:"上着を着るタイミングの話です。",lines:["ごはん…前に、上着ね。","ごはん…あとで、上着ね。"],meanings:["食事の前に上着を着たい。","食事のあとに上着を着たい。"],clues:["前に","あとで"],explanation:"『上着』は同じでも、時間を示す語によって行動の順番が変わります。",asks:["ごはんの前に着ますか？","ごはんのあとに着ますか？"],trap:"上着を着たくない。"},
 {id:"past",group:"時間・条件",setting:"家族の訪問について話しています。",lines:["娘…きのう、来たの。","娘…あした、来るの。"],meanings:["娘が昨日来たという話。","娘が明日来るという話。"],clues:["きのう・来た","あした・来る"],explanation:"時間の語と動詞の形を合わせて聞きます。予定の確定状況は本人の発言だけで決めません。",asks:["昨日、娘さんがいらしたのですね？","明日、娘さんが来る予定なのですね？"],trap:"娘の訪問日を話していない。"},
 {id:"rain",group:"時間・条件",setting:"外に出る予定について話しています。",lines:["雨なら…やめとこう。","雨でも…行きたいね。"],meanings:["雨の場合は外出をやめたい。","雨の場合でも外出したい。"],clues:["なら・やめとこう","でも・行きたい"],explanation:"条件を表す『なら』と、条件にかかわらない希望を表す『でも』を区別します。",asks:["雨だったら、外に出るのはやめますか？","雨でも外に出たい、ということですか？"],trap:"天気に関係なく外出を断っている。"},
 {id:"side",group:"場所・量",setting:"棚に赤い本が左右に一冊ずつあります。",lines:["右の…赤いの、取って。","左の…赤いの、取って。"],meanings:["右側の赤い本を求めている。","左側の赤い本を求めている。"],clues:["右","左"],explanation:"色だけでは本を選べません。左右は相手から見た向きかも含め、現物を示して確かめます。",asks:["この赤い本で合っていますか？","この赤い本で合っていますか？"],trap:"赤い本はいらない。"},
 {id:"amount",group:"場所・量",setting:"湯のみへお茶を入れる量の話です。",lines:["お茶…少しだけね。","お茶…もう少しね。"],meanings:["入れる量を少なくしてほしい。","今の量から、少し増やしてほしい。"],clues:["少しだけ","もう少し"],explanation:"似た表現でも、『だけ』は量を抑える希望、『もう』は追加する希望です。",asks:["このくらいの少量でよいですか？","あと少し入れますか？"],trap:"お茶を全部片づけてほしい。"},
 {id:"curtain",group:"場所・量",setting:"カーテンについて頼まれました。",lines:["カーテン…少し開けて。","カーテン…少し閉めて。"],meanings:["カーテンを少し開けてほしい。","カーテンを少し閉めてほしい。"],clues:["開けて","閉めて"],explanation:"対象と量が同じでも、動作が逆になります。聞き取れた名詞だけで行動を決めません。",asks:["少し開けますか？","少し閉めますか？"],trap:"カーテンを全部取り外してほしい。"},
 {id:"call",group:"関係・言い直し",setting:"職員に電話のことを伝えようとしています。",lines:["娘から…電話、あったよ。","娘へ…電話、お願い。"],meanings:["娘から電話があったという報告。","娘に電話をしてほしいという依頼。"],clues:["から・あった","へ・お願い"],explanation:"『から』は起点、『へ』は相手・方向。報告なのか依頼なのかも、後ろのことばで変わります。",asks:["娘さんから電話があった、ということですね？","娘さんに電話してほしい、ということですか？"],trap:"電話の相手は職員だと確定した。"},
 {id:"repair",group:"関係・言い直し",setting:"飲み物の希望を聞いています。",lines:["水…じゃなくて、お茶。","お茶…じゃなくて、水。"],meanings:["言い直したあとの希望はお茶。","言い直したあとの希望は水。"],clues:["じゃなくて・お茶","じゃなくて・水"],explanation:"先に出た名詞をそのまま採用せず、『じゃなくて』のあとの訂正を聞きます。",asks:["お茶ですね？","お水ですね？"],trap:"両方の飲み物を希望している。"},
 {id:"family",group:"関係・言い直し",setting:"家族の写真を見ています。",lines:["娘…いや、孫だね。","孫…いや、娘だね。"],meanings:["言い直したあとは孫だと言っている。","言い直したあとは娘だと言っている。"],clues:["いや・孫","いや・娘"],explanation:"『いや』のあとで情報が修正されています。最初の発言と訂正を混ぜないようにします。",asks:["この写真はお孫さんですね？","この写真は娘さんですね？"],trap:"娘と孫が二人写っているとわかった。"},
 {id:"which",group:"省略・未確認",setting:"ひざ掛けと上着が、椅子のそばにあります。",lines:["寒い…それ、お願い。","寒い…ひざ掛け、お願い。"],meanings:["寒いが、求めている物はまだ特定できない。","ひざ掛けを求めている。"],clues:["それ（対象が未確認）","ひざ掛け"],explanation:"『それ』だけでは対象が確定しません。具体的な名詞が聞こえた場合も、使い方など必要な点を確かめます。",asks:["ひざ掛けを見せて『これですか？』と聞く。","ひざに掛けますか？"],trap:"上着を求めていると確定した。"},
];
export const drills:Drill[]=([...pairs,...extraDrills.map(x=>x.pair as Pair)]).flatMap((p,i)=>p.lines.map((utterance,j)=>{const options=[...p.meanings,p.trap];const shift=(i+j)%3;return {id:`${p.id}-${j}`,group:p.group,setting:p.setting,utterance,options:[...options.slice(shift),...options.slice(0,shift)],answer:(j-shift+3)%3,clue:p.clues[j],explanation:p.explanation,ask:p.asks[j]};}));
