import extraShorts from './content/shorts-v7.json';
export type Choice = {id:string;text:string;correct:boolean;feedback:string;reply?:string};
export type Scenario = {id:string;title:string;category:string;focus:string;level:number;person:number;setting:string;utterance:string;plain:string;english:string;keywords:string[];distractors:string[];known:string;unknown:string;meanings:Choice[];clarification:Choice[];responses:Choice[];variants:string[];report:string;custom?:boolean;reviewed:string};
export const people = [
 {name:"山田 はるさん",age:82,initial:"は",note:"お茶と手芸が好き。居間でよくお話しします。",color:"amber"},
 {name:"佐藤 正夫さん",age:79,initial:"正",note:"園芸が好き。短いことばで用事を伝えます。",color:"teal"},
 {name:"田中 文子さん",age:86,initial:"文",note:"昔の歌が好き。思い出を話してくれます。",color:"rose"},
 {name:"鈴木 昭さん",age:84,initial:"昭",note:"新聞と将棋が好き。話しながら言い直すことがあります。",color:"blue"},
];
export const categories=["生活のお願い","気持ち・雑談","言い直し・時間","困りごと・連携"];
export const sceneTitles:Record<string,string>={blanket:"居間での、ひとこと",tea:"おやつの飲み物",window:"居間に入る風",glasses:"新聞を読む前に",light:"明るい居間で",tissue:"居間からのお願い",garden:"庭を眺めながら",thanks:"お手伝いのあとに",home:"テレビを見ながら",song:"歌ったあとに",refuse:"散歩に誘ったら",family:"ご家族のお話",notwater:"飲み物を選ぶとき",later:"上着のお手伝い",left:"棚の本を取るとき",yesterday:"昼食のお話",daughter:"写真を見ながら",condition:"明日の予定",pain:"居間での困りごと",dizzy:"椅子から立つとき",toilet:"トイレへの移動",heard:"予定を伝えたとき",notfinish:"食事の途中で",handover:"職員への伝言"};
Object.assign(sceneTitles,Object.fromEntries(extraShorts.map(x=>[x.seed.id,x.sceneTitle.ja])));
export type Seed={id:string;title:string;cat:number;focus:string;person:number;setting:string;utterance:string;plain:string;english:string;keywords:string[];known:string;unknown:string;meaning:string;clarify:string;reply:string;response:string;report:string;variants:string[]};
const seeds: Seed[] = [
 {id:"blanket",title:"寒い、そこの…",cat:0,focus:"指示語・ことばの断片",person:0,setting:"居間。ひざ掛けと上着が、椅子の近くにあります。",utterance:"あれ…寒い…そこの…",plain:"寒いので、黄色いひざ掛けをひざに掛けてほしいです。",english:"I'm cold. I'd like the yellow lap blanket.",keywords:["寒い","そこの"],known:"寒いと感じている。近くの何かを求めている。",unknown:"ひざ掛けか、上着か。この発言だけでは決められない。",meaning:"寒さを感じているが、何がほしいかはまだ不明。",clarify:"黄色いひざ掛けを見せて『これですか？』と聞く。",reply:"そう、それ。ひざに、お願い。",response:"ひざに掛けますね。暑かったら教えてください。",report:"『寒い』と話された。ひざ掛けを見せて確認し、黄色いひざ掛けをひざに掛けてほしいとわかった。",variants:["そこの、黄色いの…ひざに。","冷えるねえ。あれ、掛けてくれる？"]},
 {id:"tea",title:"お茶、ちょっと…",cat:0,focus:"量の省略",person:1,setting:"おやつの時間。湯のみがあります。",utterance:"お茶…ちょっとだけ、ね。",plain:"お茶を少しだけ入れてほしいです。",english:"Please pour just a little tea.",keywords:["お茶","ちょっとだけ"],known:"お茶を求めていて、量は少しがよい。",unknown:"具体的にどのくらいの量がよいか。",meaning:"お茶を少しだけ入れてほしい。",clarify:"少し入れた湯のみを見せて『このくらいですか？』と聞く。",reply:"うん、それでいいよ。",response:"このくらい入れますね。",report:"少量のお茶を希望され、湯のみを見せて量を確認した。",variants:["いっぱいじゃなくて、少しでいいよ。","お茶、底のほうにちょこっと。"]},
 {id:"window",title:"そこ、閉めて…",cat:0,focus:"場所・指差し",person:0,setting:"居間。窓とドアが両方開いています。",utterance:"そこ…風がね…閉めて。",plain:"風が入るので、窓を閉めてほしいです。",english:"Please close the window. There is a draft.",keywords:["風","閉めて"],known:"風が気になり、何かを閉めてほしい。",unknown:"『そこ』が窓かドアか。",meaning:"何を閉めるか、確認が必要。",clarify:"窓を指して『この窓ですか？』と聞く。",reply:"そう、窓。少し寒いの。",response:"この窓を閉めますね。",report:"窓を指して確認し、窓を閉めてほしいとわかった。",variants:["風が入ってくるね。その窓ね。","そっち、窓を閉めてくれる？"]},
 {id:"glasses",title:"めがね、どこいった…",cat:0,focus:"物の所在",person:3,setting:"新聞を読もうとしています。",utterance:"めがね…さっき、ここに…どこいった。",plain:"さっき置いためがねを一緒に探してほしいです。",english:"Please help me find the glasses I put here earlier.",keywords:["めがね","さっき"],known:"めがねが見つからず、さっきは近くにあった。",unknown:"正確にどこに置いたか。",meaning:"めがねを探している。",clarify:"『さっき置いたのは、この机ですか？』と聞く。",reply:"そう、その机に置いたんだけど。",response:"この机のまわりを一緒に見てみましょう。",report:"新聞を読む前にめがねを探しており、机に置いたと話された。",variants:["読むやつ、めがねがないんだ。","めがね、机の上じゃなかったかな。"]},
 {id:"light",title:"まぶしい、そっち…",cat:0,focus:"曖昧な対象",person:2,setting:"窓から日が差し、照明もついています。",utterance:"まぶしい…そっちの、少し…",plain:"日差しがまぶしいので、カーテンを少し閉めてほしいです。",english:"Please close the curtain a little. The sunlight is bright.",keywords:["まぶしい","少し"],known:"まぶしさがあり、何かを調整してほしい。",unknown:"カーテンか照明か。",meaning:"まぶしさの原因と、調整する物を確認する。",clarify:"カーテンを指して『これを少し閉めますか？』と聞く。",reply:"うん。日が、目に入るから。",response:"少し閉めますね。このくらいでどうですか？",report:"日差しがまぶしいと話され、カーテンを少し閉めたいと確認できた。",variants:["お日さまがね。カーテン、ちょっと。","日が入るから、そこ、少し閉めて。"]},
 {id:"tissue",title:"鼻、あれ、紙…",cat:0,focus:"物の名前の省略",person:1,setting:"ティッシュ箱が机の上にあります。",utterance:"鼻…あれ、紙、そこ。",plain:"鼻をかむために、ティッシュを取ってほしいです。",english:"Please pass me a tissue for my nose.",keywords:["鼻","紙"],known:"鼻に使う紙のような物を求めている。",unknown:"求めている物がティッシュでよいか。",meaning:"ティッシュを求めている可能性があり、確認する。",clarify:"ティッシュ箱を見せて『これですか？』と聞く。",reply:"そうそう、一枚、お願い。",response:"一枚お渡ししますね。",report:"ティッシュを一枚ほしいと、物を見せて確認できた。",variants:["鼻をね、あの、ティッシュ。","紙、一枚もらえる？鼻、かみたい。"]},
 {id:"garden",title:"花、今年もねえ…",cat:1,focus:"喜びを共有する",person:1,setting:"庭の花を一緒に見ています。",utterance:"花…今年もねえ…よく咲いた。",plain:"庭の花が今年もよく咲いたことを、うれしく思っています。",english:"The garden flowers bloomed beautifully again this year.",keywords:["花","今年も"],known:"花が今年もよく咲いたと話している。",unknown:"どの花について話したいか。",meaning:"花が咲いた喜びを共有している。",clarify:"目の前の花を指して『この花、去年も咲いたんですね』と聞く。",reply:"そう。去年より、たくさんだね。",response:"本当ですね。どの花がお好きですか？",report:"庭の花について『去年よりたくさん』と話し、会話された。",variants:["今年もきれいだねえ、この花。","よく咲いたなあ。去年も見たね。"]},
 {id:"thanks",title:"いつも、悪いねえ…",cat:1,focus:"婉曲な感謝",person:0,setting:"上着を着るお手伝いをしたあとです。",utterance:"いつも…悪いねえ。助かるよ。",plain:"いつも手伝ってくれて、ありがとう。",english:"Thank you for always helping me.",keywords:["いつも","助かる"],known:"手助けが助かると伝えている。",unknown:"今、追加で手伝ってほしいことがあるか。",meaning:"手助けへの感謝を伝えている。",clarify:"『お手伝いできてよかったです。ほかに何かありますか？』と聞く。",reply:"今は大丈夫。ありがとうね。",response:"また何かあったら、教えてくださいね。",report:"上着の手伝いのあと感謝され、今はほかの希望はないと話された。",variants:["ごめんねえ、いつもありがとう。","手を貸してくれて、ありがとね。"]},
 {id:"home",title:"昔は、うちにも…",cat:1,focus:"思い出・指示語",person:2,setting:"テレビにみかんの木が映っています。",utterance:"昔は…うちにも、あったのよ。あれ。",plain:"昔、自宅にもみかんの木がありました。",english:"We used to have a mandarin orange tree at home too.",keywords:["昔","うちにも"],known:"昔、家にも何かがあったと話している。",unknown:"何があったのか。",meaning:"テレビを見て、家の思い出を話している。",clarify:"画面を指して『みかんの木ですか？』と聞く。",reply:"そう。庭にね、大きいのが。",response:"お庭にあったんですね。どんなみかんでしたか？",report:"テレビのみかんの木を見て、昔、自宅の庭にも木があったと話された。",variants:["庭にね、みかんの木があったの。","あの木、うちにもあったわ。"]},
 {id:"song",title:"あの歌、名前が…",cat:1,focus:"共有した体験",person:3,setting:"レクリエーションで歌ったあとです。",utterance:"あの歌…名前が、出てこないな。さっきの。",plain:"さっき歌った歌の題名を知りたいです。",english:"I can't remember the title of the song we just sang.",keywords:["歌","さっき"],known:"さっきの歌の名前を思い出せない。",unknown:"複数歌ったうちの、どの歌か。",meaning:"さっきの歌の題名を知りたい。",clarify:"『最後に歌った、さくらの歌ですか？』と聞く。",reply:"そう、それだ。何ていうんだっけ。",response:"『さくらさくら』です。また一緒に歌いましょうか。",report:"最後に歌った『さくらさくら』の題名を確認された。",variants:["さっきの歌、題名なんだっけ。","さくらの歌、あれ、なんていうの？"]},
 {id:"refuse",title:"今日は、いいかな…",cat:1,focus:"穏やかな断り",person:0,setting:"散歩に誘ったところです。",utterance:"今日は…いいかな。ちょっと、休んでたい。",plain:"今日は散歩をせず、休んでいたいです。",english:"I'd rather rest than go for a walk today.",keywords:["今日は","休んでたい"],known:"今日は休みたいと話している。",unknown:"別の時間なら散歩したいか。",meaning:"今の散歩の誘いを、穏やかに断っている。",clarify:"『今日はここで休みたい、ということですね？』と聞く。",reply:"うん、今日はゆっくりしたい。",response:"わかりました。ゆっくり休んでくださいね。",report:"散歩に誘った際、今日は休みたいと話され、希望を確認した。",variants:["散歩は今日はいいよ。ここにいるね。","また今度。今日はのんびりしたい。"]},
 {id:"family",title:"あの子、来るんだって…",cat:1,focus:"人・伝聞",person:2,setting:"ご家族の話をしています。",utterance:"あの子…日曜、来るんだって。楽しみ。",plain:"孫が日曜日に来ると聞いて、楽しみにしています。",english:"I heard my grandchild is coming on Sunday. I'm looking forward to it.",keywords:["日曜","楽しみ"],known:"誰かが日曜日に来ると聞き、楽しみにしている。",unknown:"『あの子』が誰か。職員側でも確認済みか。",meaning:"誰かが来ることを楽しみにしている。",clarify:"『お孫さんのことですか？』と聞く。",reply:"そう、孫。大きくなったよ。",response:"楽しみですね。最近はどんなお話をしますか？",report:"本人は孫が日曜に来ると聞いたと話された。訪問予定の職員側での確認はまだ。",variants:["孫がね、今度の日曜日に来るんだって。","あの子が来るよ。日曜、楽しみだわ。"]},
 {id:"notwater",title:"水、じゃなくて…",cat:2,focus:"否定・言い直し",person:3,setting:"飲み物を選んでいます。",utterance:"水…じゃなくて、お茶。あったかいの。",plain:"水ではなく、温かいお茶がほしいです。",english:"I'd like warm tea, not water.",keywords:["じゃなくて","お茶","あったかい"],known:"水を否定し、温かいお茶を希望している。",unknown:"どのくらいの量か。",meaning:"温かいお茶を希望している。",clarify:"『温かいお茶ですね。量は少しでいいですか？』と聞く。",reply:"うん、少しでいい。",response:"温かいお茶を少しお持ちしますね。",report:"水から温かいお茶へ言い直され、量は少しと確認できた。",variants:["お水じゃないよ。温かいお茶ね。","冷たいのはいいや。お茶、温かいの。"]},
 {id:"later",title:"今じゃ、なくて…",cat:2,focus:"時間の訂正",person:0,setting:"上着を着るお手伝いを提案しています。",utterance:"今じゃ、なくて…ごはんの、あと。",plain:"今ではなく、食事のあとに上着を着たいです。",english:"I'd like to put the jacket on after the meal, not now.",keywords:["今じゃなくて","ごはん","あと"],known:"今ではなく、食事のあとがよい。",unknown:"上着を着ることについての希望でよいか。",meaning:"食事のあとにしてほしい。",clarify:"『上着を着るのは、ごはんのあとですね？』と聞く。",reply:"そうそう、あとでお願い。",response:"ごはんのあとに、もう一度声をかけますね。",report:"上着を着る手伝いは食事のあとを希望され、再度声をかけると伝えた。",variants:["あとでいいよ。ごはんが終わってから。","今はまだ。食べてからにしよう。"]},
 {id:"left",title:"右、いや、こっち…",cat:2,focus:"方向の訂正",person:1,setting:"棚にある本を取ってほしいと言われました。",utterance:"右…いや、こっち。左の、青い。",plain:"左側にある青い本を取ってほしいです。",english:"Please pass me the blue book on the left.",keywords:["いや","左","青い"],known:"右から左へ訂正し、青い物を示している。",unknown:"どの本でよいか。",meaning:"左側の青い本を希望している。",clarify:"青い本を見せて『こちらの本ですか？』と聞く。",reply:"そう、その本。",response:"こちらの本をお渡ししますね。",report:"左側の青い本を希望され、現物を見せて確認できた。",variants:["左の、青い表紙の本だよ。","右じゃない、左。青いやつ。"]},
 {id:"yesterday",title:"昨日の、あれ…",cat:2,focus:"過去と現在",person:3,setting:"今日の昼食について話しています。",utterance:"昨日の、あれ…魚。今日は、何だい。",plain:"昨日は魚でした。今日の昼食は何ですか？",english:"We had fish yesterday. What's for lunch today?",keywords:["昨日","魚","今日は"],known:"昨日は魚で、今日の献立を尋ねている。",unknown:"今日の実際の献立。",meaning:"今日の昼食の献立を知りたい。",clarify:"『今日のお昼のメニューですね？』と聞く。",reply:"そう、今日の昼ね。",response:"献立を確認して、お伝えしますね。",report:"今日の昼食の献立を尋ねられた。昨日の話と区別し、献立を確認すると伝えた。",variants:["今日は何を食べるの？昨日は魚だったね。","お昼、今日のは何だろう。"]},
 {id:"daughter",title:"娘、じゃない、孫…",cat:2,focus:"人の言い直し",person:2,setting:"写真を一緒に見ています。",utterance:"娘…じゃない、孫。この子ね。",plain:"写真に写っているのは、娘ではなく孫です。",english:"The person in this photo is my grandchild, not my daughter.",keywords:["じゃない","孫","この子"],known:"娘ではなく、孫だと言い直している。",unknown:"どの写真の、誰を指しているか。",meaning:"写真の人を孫だと紹介している。",clarify:"指している写真を見て『こちらがお孫さんですね？』と聞く。",reply:"そう。今は高校生なの。",response:"高校生なんですね。素敵な写真ですね。",report:"写真の人物を娘から孫へ言い直され、その孫は高校生だと話された。",variants:["この子は孫よ。娘じゃなくてね。","孫なの。この写真の子ね。"]},
 {id:"condition",title:"晴れたら、外に…",cat:2,focus:"条件付きの希望",person:1,setting:"明日の予定について話しています。",utterance:"明日…晴れたら、外に。雨なら、いいよ。",plain:"明日晴れたら外に出たいですが、雨なら出なくてよいです。",english:"I'd like to go outside tomorrow if it's sunny, but not if it rains.",keywords:["明日","晴れたら","雨なら"],known:"明日、晴れた場合に外に出たい。",unknown:"明日の天気と、外に出る時間。",meaning:"晴れたら外に出たい、という条件付きの希望。",clarify:"『明日、晴れたら外に出たいのですね？』と聞く。",reply:"うん、雨なら、ここでいい。",response:"明日の天気を見て、またご相談しましょう。",report:"明日晴れたら外に出たいと希望された。時間と天気は未確定。",variants:["天気がよかったら庭に行こう。雨ならやめよう。","明日晴れたらね、外に行きたい。"]},
 {id:"pain",title:"ここ、さっきから…",cat:3,focus:"不調・決めつけない",person:0,setting:"居間。本人がおなかに手を当てています。",utterance:"ここ…さっきから、なんか…痛い。",plain:"さっきから、おなかが痛いです。",english:"My stomach has been hurting for a while.",keywords:["ここ","さっきから","痛い"],known:"どこかに、さっきから痛みがある。",unknown:"痛みの場所、程度、経過。原因はまだ不明。",meaning:"痛みの場所を確認して、職員へつなぐ。",clarify:"『痛いのは、おなかですか？』と一つずつ聞く。",reply:"うん、おなか。さっきから。",response:"おなかが痛いのですね。担当の職員に、すぐ伝えます。",report:"『さっきからおなかが痛い』と本人から聞いた。原因・程度は未確認。担当職員へ伝える。",variants:["おなかがね、痛いの。さっきから。","ここ、おなか、なんか痛くて。"]},
 {id:"dizzy",title:"立つと、ふわっと…",cat:3,focus:"感覚・職員との連携",person:3,setting:"椅子から立とうとしています。",utterance:"立つと…ふわっと、する。今は、座ってたい。",plain:"立つとふらつく感じがするので、今は座っていたいです。",english:"I feel unsteady when I stand. I'd like to stay seated now.",keywords:["立つと","ふわっと","座ってたい"],known:"立つと違和感があり、今は座りたい。",unknown:"具体的な症状、経過、原因。",meaning:"今は座っていたい。様子を確認し職員へ伝える。",clarify:"『立つと、ふらつく感じですか？』と聞く。",reply:"うん。座ってると、大丈夫。",response:"今は座っていてくださいね。担当の職員に伝えます。",report:"立つとふらつく感じがあり、座っていると大丈夫と本人は話された。原因は未確認。職員へ伝える。",variants:["立つとふらっとするね。座っていようかな。","今は座っていたい。立つと、ふわっとして。"]},
 {id:"toilet",title:"トイレ、でも一人は…",cat:3,focus:"希望と不安",person:1,setting:"トイレに行きたいと話しています。",utterance:"トイレ…行きたい。でも、一人は…ちょっと。",plain:"トイレに行きたいですが、一人で行くのは不安です。",english:"I need to use the toilet, but I don't feel comfortable going alone.",keywords:["トイレ","一人","ちょっと"],known:"トイレに行きたい。一人についてためらっている。",unknown:"どんな手伝いが必要か。",meaning:"トイレに行くための手助けを求めている。",clarify:"『一緒に来てほしいですか？』と聞く。",reply:"うん、一緒にお願い。",response:"一緒に行けるよう、担当の職員に声をかけますね。",report:"トイレに行きたく、一緒に来てほしいと確認できた。施設の介助手順に沿って職員へつなぐ。",variants:["トイレに付き合ってもらえるかな。","一人は不安だから、一緒に来て。"]},
 {id:"heard",title:"え？もう一回…",cat:3,focus:"聞こえ方・環境",person:2,setting:"テレビがついている居間で、予定を伝えています。",utterance:"え？…もう一回。テレビ、うるさくて。",plain:"テレビの音で聞こえなかったので、もう一度言ってほしいです。",english:"I couldn't hear over the TV. Please say that again.",keywords:["もう一回","テレビ","うるさくて"],known:"テレビの音で聞き取りづらく、もう一度聞きたい。",unknown:"どの部分を聞き取れなかったか。",meaning:"周りの音を減らして、もう一度伝える。",clarify:"『テレビの音を少し下げてもいいですか？』と聞く。",reply:"うん、お願い。",response:"音を下げますね。それから、もう一度ゆっくりお伝えします。",report:"テレビの音で聞こえないと話された。音を下げることを了承され、予定を伝え直す。",variants:["テレビで聞こえなかった。もう一度お願い。","音が大きくてね。今の、なんだって？"]},
 {id:"notfinish",title:"もう、いらん…",cat:3,focus:"拒否・残る疑問",person:3,setting:"食事中。お皿に食べ物が残っています。",utterance:"もう、いらん…これ、かたい。",plain:"これは硬く感じるので、これ以上食べたくありません。",english:"I don't want any more of this. It feels hard to eat.",keywords:["もう","いらん","かたい"],known:"これ以上は不要で、何かが硬いと感じている。",unknown:"何が硬いか。ほかの物なら食べたいか。",meaning:"硬さが気になり、これ以上は食べたくない。",clarify:"お皿を指して『このおかずが硬いですか？』と聞く。",reply:"うん。このおかず、今日はもういい。",response:"わかりました。硬かったことを担当の職員に伝えますね。",report:"このおかずは硬く、今日はもう食べたくないと確認した。ほかの食べ物の希望は未確認。",variants:["このおかずは、もういいよ。硬くて。","かたいから、これ以上はいらない。"]},
 {id:"handover",title:"さっきの人に、伝えて…",cat:3,focus:"人・伝言の確認",person:0,setting:"先ほど別の職員と話していました。",utterance:"さっきの人に…娘、電話ね。伝えて。",plain:"先ほど話した職員に、娘に電話したいと伝えてほしいです。",english:"Please tell the staff member I spoke to earlier that I want to call my daughter.",keywords:["さっきの人","娘","電話"],known:"先ほどの人への、娘と電話に関する伝言がある。",unknown:"誰への伝言か。娘から電話か、娘へ電話か。",meaning:"電話に関する伝言の向きと、相手を確認する。",clarify:"『娘さんに電話をしたい、ということですか？』と聞く。",reply:"そう。さっき話した職員さんに、お願い。",response:"先ほどの職員を確認して、電話したいことを伝えますね。",report:"本人は娘に電話したいと希望。先ほど話した職員に伝えてほしいとのこと。職員の名前は未確認。",variants:["娘に電話したいって、あの職員さんに伝えて。","さっきの職員さんに、電話のこと、お願い。"]},
];
function rotate<T>(a:T[],n:number){return [...a.slice(n),...a.slice(0,n)];}
const listeningTraps:Record<string,string[]>={blanket:["暑い","お茶"],tea:["いっぱい","お水"],window:["開けて","暑い"],glasses:["明日","新聞"],light:["暗い","全部"],tissue:["髪","花"],garden:["今年は","枯れた"],thanks:["いつまで","困る"],home:["今は","海にも"],song:["明日","出かけたい"],refuse:["行ってたい","昨日は"],family:["土曜","寂しい"],notwater:["冷たい","水がほしい"],later:["前","今すぐ"],left:["赤い","右の"],yesterday:["明日は","肉"],daughter:["娘で合っている","妹"],condition:["雨でも","今日"],pain:["かゆい","昨日から"],dizzy:["座ると","立ってたい"],toilet:["一人でいい","おふろ"],heard:["もういい","静かで"],notfinish:["やわらかい","もっと"],handover:["娘から","あとでいい"]};
const meaningTraps:Record<string,string[]>={
 blanket:["黄色いひざ掛けがほしい、とすでに確定している。","近くの上着を着たい、とすでに確定している。"],
 tea:["湯のみいっぱいのお茶を希望している。","お茶はいらないので、片づけてほしい。"],
 window:["ドアを閉めてほしい、とすでに確定している。","窓を開けて、風を入れてほしい。"],
 glasses:["めがねを買いに行きたい。","これからめがねを机に置いてほしい。"],
 light:["照明を全部消してほしい、と確定している。","暗いので、カーテンを開けてほしい。"],
 tissue:["新聞を取ってほしい、と確定している。","鼻が痛い原因まで、発言からわかった。"],
 garden:["花が咲かないので、困っている。","すぐに花を切って、部屋に飾ってほしい。"],
 thanks:["手伝ったことを、怒っている。","もう手伝わなくてよい、と断っている。"],
 home:["テレビを消してほしい。","今、自宅に帰りたいと頼んでいる。"],
 song:["歌うことを、もうやめたい。","さっきの歌を、職員に作ってほしい。"],
 refuse:["今日の散歩の誘いに、賛成している。","散歩そのものを、今後ずっと断っている。"],
 family:["職員に、日曜に必ず来るよう頼んでいる。","孫の訪問が施設でも確定した、とわかった。"],
 notwater:["最初に水と言ったので、水を希望している。","冷たいお茶を希望している。"],
 later:["食事の前に、すぐ上着を着たい。","食事のあとも、上着は着たくない。"],
 left:["右側の青い本を希望している。","左側の赤い本を希望している。"],
 yesterday:["昨日の魚を、もう一度持ってきてほしい。","今日の献立は魚だ、と教えてくれている。"],
 daughter:["写真に写っているのは、娘だと言っている。","写真の人が娘か孫か、言い直したあとも全く不明。"],
 condition:["明日は天気に関係なく、必ず外に出たい。","雨が降ったら、外に出たい。"],
 pain:["原因は食べすぎだとわかった。","さっきの痛みは、今は治ったと言っている。"],
 dizzy:["今、すぐに立って歩きたい。","座っているときだけ、ふらつくと言っている。"],
 toilet:["一人でトイレへ行きたい。","トイレには行きたくない。"],
 heard:["話を終えてほしい。","テレビをもっと大きな音にしてほしい。"],
 notfinish:["おかずを、もっと食べたい。","これからの食事を、すべて断っている。"],
 handover:["娘から電話が来た、とすでに確定している。","娘に、職員へ電話するよう伝えてほしい。"],
};
const responseTraps:Record<string,string>={blanket:"寒いんですね。では、上着を着ましょう。",tea:"湯のみいっぱいに入れますね。",window:"では、ドアを閉めますね。",glasses:"めがねは、もう探さなくていいですね。",light:"照明を全部消しますね。",tissue:"新聞をお渡ししますね。",garden:"今年は花が咲かなくて残念ですね。",thanks:"それでは、もうお手伝いしませんね。",home:"今すぐ、ご自宅に帰りましょう。",song:"では、もう歌わないようにしますね。",refuse:"散歩ですね。今、出かけましょう。",family:"日曜の訪問は、必ずありますよ。",notwater:"お水を少しお持ちしますね。",later:"上着は今すぐ着ましょう。",left:"右の青い本をお渡ししますね。",yesterday:"今日も魚ですよ。確認しなくても大丈夫です。",daughter:"娘さんは高校生なのですね。",condition:"雨でも、明日は必ず外へ行きましょう。",pain:"食べすぎでしょう。職員に伝えなくても大丈夫です。",dizzy:"今は立って歩いてみましょう。",toilet:"一人で行ってみてくださいね。",heard:"テレビの音はそのままで、同じ速さでもう一度言いますね。",notfinish:"もう少し、同じおかずを食べましょう。",handover:"娘さんから電話が来たと、伝えておきますね。"};
Object.assign(listeningTraps,Object.fromEntries(extraShorts.map(x=>[x.seed.id,x.traps.listening])));
Object.assign(meaningTraps,Object.fromEntries(extraShorts.map(x=>[x.seed.id,x.traps.meanings])));
Object.assign(responseTraps,Object.fromEntries(extraShorts.map(x=>[x.seed.id,x.traps.response])));
export function makeScenario(s:Seed,i=0):Scenario {
 return {id:s.id,title:s.title,category:categories[s.cat],focus:s.focus,level:s.cat<2?1:s.cat===2?2:3,person:s.person,setting:s.setting,utterance:s.utterance,plain:s.plain,english:s.english,keywords:s.keywords,known:s.known,unknown:s.unknown,variants:s.variants,report:s.report,reviewed:"作成例・現場監修待ち",
 distractors:listeningTraps[s.id]||["明後日","電話を切る"],
 meanings:rotate([{id:"m-correct",text:s.meaning,correct:true,feedback:`聞き取れたこと：${s.known}`},{id:"m-guess",text:meaningTraps[s.id]?.[0]||"細かい希望もすべてわかったので、確認せずに進める。",correct:false,feedback:`発言からわかるのは：${s.known} まだ不明なのは：${s.unknown}`},{id:"m-dismiss",text:meaningTraps[s.id]?.[1]||"ことばが途切れているので、希望はないと判断する。",correct:false,feedback:`省略されたことばや、言い直しのあとに注目しましょう。${s.known}`}],i%3),
 clarification:rotate([{id:"q-good",text:s.clarify,correct:true,reply:s.reply,feedback:"具体的に確かめました。相手の返答で、理解を更新できます。"},{id:"q-many",text:"『いつ、どれ、どうして、どうしたいですか？』と一度に聞く。",correct:false,reply:"ええと…どれのこと？",feedback:"質問が重なると、何に答えるか迷いやすくなります。短く一つずつ聞きましょう。"},{id:"q-assume",text:s.cat===1?"『もういいですね』と話を終える。":"『わかりました』だけで、確認せず進める。",correct:false,reply:"え？…ちょっと、違うんだけど。",feedback:"見えている物や、聞き取れたことばを使って確かめましょう。"}],(i+1)%3),
 responses:rotate([{id:"r-good",text:s.response,correct:true,feedback:"確認できた希望を受け止め、次の行動を短く伝えられました。"},{id:"r-assume",text:responseTraps[s.id]||"確認していないことも、すべてわかったと伝える。",correct:false,feedback:`確認できた希望は「${s.plain}」。相手が確認してくれた内容を使いましょう。`},{id:"r-stop",text:"『わかりました』だけ言って、次にどうするか伝えない。",correct:false,feedback:"この練習では、確認できたことと次の行動を一言添えてみましょう。"}],(i+2)%3)};
}
export const scenarios=[...seeds,...extraShorts.map(x=>x.seed)].map(makeScenario);
