import extraShorts from './content/shorts-v7.json';
import {scenarios,sceneTitles} from './scenarios';
// Display translations only. Japanese audio scripts remain unchanged.
const rows:Record<string,string[]>={
blanket:["A few words in the lounge","Pointing words and fragments","A lap blanket and a jacket are near the chair in the lounge.","They feel cold and want something nearby.","Whether they want the blanket or the jacket is not yet clear.","They feel cold, but the item they want is still unknown.","Show the yellow lap blanket and ask, 'Is this the one?'","I'll put it on your lap. Please tell me if you feel too warm.","They said they felt cold. Showing the yellow lap blanket confirmed that they wanted it on their lap.","It is already certain that they want the yellow lap blanket.","It is already certain that they want to wear the nearby jacket.","You feel cold. Let's put on your jacket."],
tea:["A drink at snack time","An unstated amount","It is snack time. A teacup is available.","They want a small amount of tea.","The exact amount is still unknown.","They want just a little tea.","Show a cup with a little tea and ask, 'About this much?'","I'll pour this much.","They asked for a little tea. The amount was confirmed by showing the cup.","They want a full cup of tea.","They do not want tea and want it cleared away.","I'll fill the cup to the top."],
window:["A draft in the lounge","Place and pointing","Both the window and the door are open in the lounge.","The draft bothers them; they want something closed.","Whether 'there' means the window or the door.","We need to check what they want closed.","Point to the window and ask, 'This window?'","I'll close this window.","Pointing to the window confirmed which opening they wanted closed.","It is already certain that they want the door closed.","They want the window opened to let in a draft.","Then I'll close the door."],
glasses:["Before reading the newspaper","Finding an object","They are about to read the newspaper.","Their glasses are missing; they were nearby earlier.","The exact place where they put them.","They are looking for their glasses.","Ask, 'Was this the table where you put them?'","Let's look around this table together.","Before reading, they looked for their glasses and said they had put them on the table.","They want to buy new glasses.","They want you to put their glasses on the table now.","We don't need to look for your glasses anymore."],
light:["A bright lounge","An unclear object","Sunlight comes through the window and the lights are also on.","The brightness bothers them; they want an adjustment.","Whether they mean the curtain or the lights.","Check what is too bright and what should be adjusted.","Point to the curtain and ask, 'Shall I close this a little?'","I'll close it a little. How is this?","They said sunlight was too bright and confirmed they wanted the curtain partly closed.","It is certain that they want all the lights switched off.","It is dark, so they want the curtains opened.","I'll switch off all the lights."],
tissue:["A request in the lounge","An omitted object name","A tissue box is on the table.","They want a paper-like item for their nose.","Whether the item they want is a tissue.","They may want a tissue; confirm the object.","Show the tissue box and ask, 'Is this it?'","I'll give you one tissue.","Showing the object confirmed that they wanted one tissue.","It is certain that they want a newspaper.","We have already learned the cause of pain in their nose.","I'll pass you the newspaper."],
garden:["Looking at the garden","Sharing happiness","You are looking at the garden flowers together.","They say the flowers have bloomed well again this year.","Which flowers they want to talk about.","They are sharing their pleasure at the flowers.","Point to the flowers and ask, 'These bloomed last year too?'","They really are lovely. Which flowers do you like?","They talked about the garden flowers and said there were more than last year.","They are upset because the flowers did not bloom.","They want the flowers cut immediately for their room.","It's a shame the flowers did not bloom this year."],
thanks:["After offering help","Indirect thanks","You have just helped them put on a jacket.","They say the help is appreciated.","Whether they need any further help now.","They are thanking you for helping.","Say, 'I'm glad I could help. Is there anything else?'","Please tell me if you need anything else.","After help with a jacket, they expressed thanks and said they needed nothing else now.","They are angry that you helped.","They are refusing all further help.","Then I won't help you anymore."],
home:["Watching television","Memories and pointing words","A mandarin orange tree is shown on television.","They say they used to have something at home.","What object they mean.","The television has brought up a memory of home.","Point to the screen and ask, 'A mandarin orange tree?'","You had one in your garden. What were the oranges like?","Seeing the tree on television, they said they used to have one in their garden.","They want the television turned off.","They are asking to go home immediately.","Let's go to your home right now."],
song:["After singing together","A shared experience","A singing activity has just finished.","They cannot remember the title of a song sung earlier.","Which song they mean, because several were sung.","They want to know the title of the song.","Ask, 'The cherry-blossom song we sang last?'","It's Sakura Sakura. Shall we sing it again together?","They asked for the title of Sakura Sakura, the last song sung.","They do not want to sing anymore.","They want a staff member to compose the song.","Then let's stop singing."],
refuse:["An invitation for a walk","A gentle refusal","You have invited them for a walk.","They say they want to rest today.","Whether they might want a walk at another time.","They are politely declining the current invitation.","Ask, 'You'd like to rest here today, is that right?'","Of course. Please enjoy your rest.","When invited for a walk, they said they preferred to rest today; this was confirmed.","They accept today's invitation for a walk.","They are refusing every walk from now on.","A walk, then. Let's go now."],
family:["Talking about family","A person and reported information","You are talking about their family.","They have heard someone is coming on Sunday and look forward to it.","Who 'that child' is; whether staff have confirmed the visit.","They are looking forward to someone's visit.","Ask, 'Do you mean your grandchild?'","That sounds lovely. What do you talk about these days?","They said they had heard their grandchild would visit on Sunday. Staff confirmation is still pending.","They are asking a staff member to visit on Sunday without fail.","The visit has definitely been confirmed by the facility.","The Sunday visit will definitely happen."],
notwater:["Choosing a drink","Negation and correction","They are choosing a drink.","They corrected water to warm tea.","How much tea they want.","They want warm tea.","Ask, 'Warm tea. Is a little enough?'","I'll bring a little warm tea.","They corrected water to warm tea and confirmed that a small amount was enough.","They first said water, so they want water.","They want cold tea.","I'll bring a little water."],
later:["Helping with a jacket","Correcting the time","You have offered help putting on a jacket.","They want it after the meal, not now.","Whether this timing refers to putting on the jacket.","They want the help after the meal.","Ask, 'Putting on the jacket after your meal, is that right?'","I'll ask you again after your meal.","They wanted help with the jacket after eating; you said you would ask again then.","They want to wear the jacket right now before eating.","They do not want the jacket even after eating.","Let's put the jacket on now."],
left:["Choosing a book from a shelf","Correcting direction","They have asked for a book from the shelf.","They corrected right to left and mentioned a blue object.","Which particular book they want.","They want the blue book on the left.","Show the blue book and ask, 'This book?'","I'll pass you this book.","They wanted the blue book on the left; the exact book was confirmed by showing it.","They want the blue book on the right.","They want the red book on the left.","I'll pass you the blue book on the right."],
yesterday:["Talking about lunch","Past and present","You are talking about today's lunch.","Yesterday's lunch was fish; they are asking about today's menu.","What is actually on today's menu.","They want to know today's lunch menu.","Ask, 'You mean today's lunch menu?'","I'll check the menu and tell you.","They asked about today's lunch. You distinguished this from yesterday's meal and said you would check.","They want yesterday's fish brought again.","They are telling you today's menu is fish.","It's fish again today. There's no need to check."],
daughter:["Looking at a family photo","Correcting a person","You are looking at photographs together.","They corrected daughter to grandchild.","Which person in which photograph they mean.","They are introducing the person as their grandchild.","Look at the indicated photo and ask, 'This is your grandchild?'","A high-school student now. What a lovely photograph.","They corrected daughter to grandchild and said the grandchild is now in high school.","They say the person in the picture is their daughter.","Even after the correction, it is entirely unclear whether they mean daughter or grandchild.","Your daughter is in high school, then."],
condition:["Tomorrow's plans","A conditional wish","You are talking about tomorrow's plans.","They want to go outside tomorrow if it is sunny.","Tomorrow's weather and the time to go out.","They want to go outside on the condition that it is sunny.","Ask, 'You'd like to go outside tomorrow if it's sunny?'","Let's check tomorrow's weather and discuss it again.","They wanted to go outside tomorrow if sunny. The weather and time are not yet confirmed.","They definitely want to go outside regardless of the weather.","They want to go outside if it rains.","Let's definitely go outside tomorrow, even in the rain."],
pain:["A concern in the lounge","Discomfort without guessing a cause","In the lounge, they have a hand on their abdomen.","They have had pain somewhere for a little while.","Location, severity, progression, and cause are not yet known.","Check the location and inform the responsible staff member.","Ask one question: 'Is the pain in your abdomen?'","Your abdomen hurts. I'll tell the responsible staff member straight away.","They said their abdomen had hurt for a while. Cause and severity are unconfirmed. This needs to be passed to staff.","We know the cause is overeating.","They say the earlier pain is now gone.","It must be overeating. We don't need to tell staff."],
dizzy:["When getting up from a chair","A sensation and staff communication","They are about to rise from a chair.","Standing causes an unusual sensation; they want to remain seated now.","The precise symptoms, progression, and cause.","They want to remain seated; check their account and inform staff.","Ask, 'Do you feel unsteady when you stand?'","Please stay seated for now. I'll tell the responsible staff member.","They reported unsteadiness when standing and said they felt all right seated. The cause is unconfirmed; inform staff.","They want to stand and walk immediately.","They only feel unsteady when seated.","Let's try standing and walking now."],
toilet:["Going to the toilet","A wish and hesitation","They say they need to go to the toilet.","They want to use the toilet and hesitate about going alone.","What help they need.","They are asking for support to go to the toilet.","Ask, 'Would you like someone to come with you?'","I'll ask the responsible staff member to arrange that.","They confirmed they wanted someone to accompany them to the toilet. Follow the facility's assistance procedure.","They want to go alone.","They do not want to go to the toilet.","Please try going on your own."],
heard:["Explaining a plan","Hearing and the environment","You are explaining a plan in a lounge with the television on.","The television makes it hard to hear; they want you to repeat.","Which part they did not hear.","Reduce competing sound and explain again.","Ask, 'May I turn the TV volume down a little?'","I'll turn it down, then repeat slowly.","They said the TV prevented hearing. They agreed to lower the volume; the plan will be repeated.","They want the conversation ended.","They want the TV volume increased.","I'll keep the TV volume and repeat at the same speed."],
notfinish:["During a meal","A refusal with questions remaining","Food remains on the plate during a meal.","They want no more of something and find it hard.","Which food is hard; whether they want something else.","The hardness bothers them and they do not want more of it.","Point to the dish and ask, 'Is this dish hard?'","Of course. I'll tell the responsible staff member that it felt hard.","They confirmed this dish was hard and they wanted no more today. Wishes about other food remain unconfirmed.","They want more of the dish.","They are refusing every future meal.","Let's eat a little more of the same dish."],
handover:["A message for a staff member","Checking people and a message","They were talking to another staff member earlier.","They have a message about their daughter and a telephone call.","Which staff member; whether the call is from or to their daughter.","Check who the message is for and the direction of the call.","Ask, 'You would like to call your daughter?'","I'll find the staff member you spoke to and pass on your wish to call.","They wanted to call their daughter and asked for this to be passed to the earlier staff member. The staff member's name is unconfirmed.","It is already certain their daughter called them.","They want their daughter to tell a staff member to call.","I'll tell staff that your daughter called."],
};
Object.assign(rows,Object.fromEntries(extraShorts.map(x=>[x.seed.id,x.englishRows])));
export const scenarioDictionary:Record<string,string>={};
for(const s of scenarios){const e=rows[s.id];if(!e)continue;const target=scenarioDictionary;
 target[sceneTitles[s.id]]=e[0];target[s.focus]=e[1];target[s.setting]=e[2];target[s.known]=e[3];target[s.unknown]=e[4];target[s.meanings.find(c=>c.correct)!.text]=e[5];target[s.clarification.find(c=>c.correct)!.text]=s.clarification.find(c=>c.correct)!.text+'\n'+e[6];target[s.responses.find(c=>c.correct)!.text]=s.responses.find(c=>c.correct)!.text+'\n'+e[7];target[s.report]=s.report+'\n'+e[8];target[s.meanings.find(c=>c.id==='m-guess')!.text]=e[9];target[s.meanings.find(c=>c.id==='m-dismiss')!.text]=e[10];target[s.responses.find(c=>c.id==='r-assume')!.text]=s.responses.find(c=>c.id==='r-assume')!.text+'\n'+e[11];target[s.plain]=s.plain+'\n'+s.english;
}
